### PR TITLE
fix: disallow qualified name in try-catch

### LINKED ISSUE #9685: Is qualified name allowed in try catch?
First mentioned in #9674, magnus suggests that we should not allow unqualified name in try catch.

Actually the example code is from the book https://doc.flix.dev/exceptions.html?highlight=try%20catch#exceptions.

But the fact is, both qualified name and unqualified name now works fine:
image

image

### PR DESCRIPTION
**Pull request by stormckey**
fixes #9685

Now the parser will not accept qualified name in try catch:
image

But the error message is helpless, how could we improve this?

### CODE REVIEW

File: main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala [hunk 1]
```diff
@@ -1781,9 +1781,11 @@ object Weeder2 {
 
     private def visitTryCatchRule(tree: Tree)(implicit sctx: SharedContext): Validation[CatchRule, CompilationMessage] = {
       expect(tree, TreeKind.Expr.TryCatchRuleFragment)
-      mapN(pickNameIdent(tree), pickQName(tree), pickExpr(tree)) {
-        (ident, qname, expr) => CatchRule(ident, javaQnameToFqn(qname), expr)
+      val idents = pickAll(TreeKind.Ident, tree).map(tokenToIdent)
+      mapN(pickExpr(tree)){
+        expr => CatchRule(idents.head, idents.last, expr)
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala:1786]: I think this can fail. You should match on idents and check that there are two. If not, we have to produce some error.

Comment (stormckey) [reply main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala:1786]: Is there an appropriate error or we should create one?

Comment (magnus-madsen) [reply main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala:1786]: I think we have to create one

Comment (magnus-madsen) [reply main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala:1786]: But you should experiment. Maybe the case cannot happen (?) Try write some partial catch rules and see how the weeder behaves

Comment (stormckey) [reply main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala:1786]: Acctually I now has another idea: what if we parse a qualified name here and then check if it's qualified. This code will looks like:
```
      mapN(pickNameIdent(tree), pickQName(tree), pickExpr(tree)) {
        case (ident, qname, expr) if qname.isUnqualified => CatchRule(ident, qname.ident, expr)
        case _ =>
          val error = IllegalQualifiedName(tree.loc)
          sctx.errors.add(error)
          CatchRule(Name.Ident("error", tree.loc), Name.Ident("error", tree.loc), Expr.Error(error))
      }
``` 
and the error will looks like:
image

Comment (stormckey) [reply main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala:1786]: I created a fake CatchRule when the name is qualified and that triggered the resolution error since that java class doesn't exist. How should we handle this?

Comment (stormckey) [reply main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala:1786]: This way the error when there is only one ident is:
image

Comment (stormckey) [reply main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala:1786]: what do you think @magnus-madsen

Comment (magnus-madsen) [reply main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala:1786]: Let me get back to you :)

Comment (stormckey) [reply main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala:1786]: Beep

**Comment by stormckey** [comment]
Now the error message will be :
image

The second one needs improvement, but not in this PR :)

**Review by magnus-madsen — APPROVED** [review]

**Comment by magnus-madsen** [comment]
Conflicted but otherwise good to go
