### PR TITLE
fix: Entrypoints handles malformed types

### LINKED ISSUE #9589: EntryPoints must support malformed types
```
ca.uwaterloo.flix.util.InternalCompilerException: Unexpected effect 'Error'.
	at ca.uwaterloo.flix.language.phase.EntryPoints$CheckEntryPoints$.eval(EntryPoints.scala:384)
	at ca.uwaterloo.flix.language.phase.EntryPoints$CheckEntryPoints$.isPrimitiveEffect(EntryPoints.scala:348)
```

### PR DESCRIPTION
**Pull request by JonathanStarup**
fixes #9589

I've removed most of the `throw` cases in the phase by handling malformed/error types explicitly. It is verbose but clear IMO

### CODE REVIEW

File: main/src/ca/uwaterloo/flix/language/phase/EntryPoints.scala [hunk 1]
```diff
@@ -568,15 +591,42 @@ object EntryPoints {
...
+      case EvalRes.ErrorOrMalformed => EvalRes.ErrorOrMalformed
+    }
+
+    def flatMap[B](f: T => EvalRes[B]): EvalRes[B] = this match {
+      case EvalRes.Ok(x) => f(x)
+      case EvalRes.ErrorOrMalformed => EvalRes.ErrorOrMalformed
     }
+  }
+
+  object EvalRes {
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/phase/EntryPoints.scala:616]: Any reason not to use Option or Result?

Comment (magnus-madsen) [reply main/src/ca/uwaterloo/flix/language/phase/EntryPoints.scala:616]: I think our own Result would fit here.

Comment (JonathanStarup) [reply main/src/ca/uwaterloo/flix/language/phase/EntryPoints.scala:616]: I had separate cases for Error and Malformed previously - but it also avoids option blindness or whatever it is called. You want me to just use Result?

Comment (JonathanStarup) [reply main/src/ca/uwaterloo/flix/language/phase/EntryPoints.scala:616]: In this case it would also be `Result[T, Unit]` or `Option`

Comment (magnus-madsen) [reply main/src/ca/uwaterloo/flix/language/phase/EntryPoints.scala:616]: I think the nicest thing you can do is:

```
case object MyError
Result[t, MyError]
```

Its precise, monadic, and extendable.

Comment (JonathanStarup) [reply main/src/ca/uwaterloo/flix/language/phase/EntryPoints.scala:616]: That's true, but sometimes you also don't like that I have results of options etc. so I don't think its black and white.

In this case I have no error information, so here it would just be
```
case object ErrorOrMalformed
Result[T, ErrorOrMalformed]
```
should I do that change?

Comment (magnus-madsen) [reply main/src/ca/uwaterloo/flix/language/phase/EntryPoints.scala:616]: Seems better than what it is

Comment (JonathanStarup) [reply main/src/ca/uwaterloo/flix/language/phase/EntryPoints.scala]: I've implemented it now - I forgot that the type of `ErrorOrMalformed` is `ErrorOrMalformed.type`

**Review by magnus-madsen — APPROVED** [review]

**Comment by magnus-madsen** [comment]
I think this turned out well.

**Comment by magnus-madsen** [comment]
@JonathanStarup There is a small conflict, but otherwise this is ready to go.
