### PR TITLE
fix: reject `par` `Apply` instead of crashing

### LINKED ISSUE #4491: `Par` expression crashes
This program:

```
def main(): Unit \ IO = 
    List.range(1, 100) |> parMap(x -> x + 1) |> println

def parMap(f: a -> b, l: List[a]): List[b] = match l {
    case Nil            => Nil
    case Cons(x, xs)    => Cons(par f(x), parMap(f, xs))
}
```

should be rejected, but not crash the compiler. (Probably an easy fix).

### PR DESCRIPTION
**Pull request by jaschdoc**
Closes  #4491

### CODE REVIEW

File: main/src/ca/uwaterloo/flix/language/phase/Safety.scala [hunk 1]
```diff
@@ -255,9 +255,6 @@ object Safety {
     case Expression.Par(exp: Expression.Tuple, _) =>
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/phase/Safety.scala:255]: I would like to have just one Par case where you match on the inner expression and then a comment that explains what is happening :)

**Comment by jaschdoc** [comment]
fixed
