### PR TITLE
fix: cycle detection bug

### LINKED ISSUE #3179: Wrong stratification error
```flix
def main(_args: Array[String]): Int32 & Impure =
    let p = #{
        T(12). A(;12).
        R(x) :- T(x), not C(x).
        C(x) :- T(x), not B(x).
        B(x) :- T(x), A(;x).
        B(x) :- not B(x).
    };
    query p select x from B(x) |> println;
    println("Hello World!");
    0
```

This program reports that there is a negative cycle between `C` and `C`, both in line 4.

### PR DESCRIPTION
**Pull request by JonathanStarup**
Fixed #3179

### CODE REVIEW

File: main/src/ca/uwaterloo/flix/language/phase/UllmansAlgorithm.scala [hunk 1]
```diff
@@ -116,7 +117,7 @@ object UllmansAlgorithm {
               changed = true
             }
 
-          case DependencyEdge.Strong(headSym, bodySym, edgeLoc) =>
+          case currentEdge@DependencyEdge.Strong(headSym, bodySym, _) =>
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/phase/UllmansAlgorithm.scala:120]: We usually dont use `@` variables. You already have `edge` in scope here.

File: main/src/ca/uwaterloo/flix/language/phase/UllmansAlgorithm.scala [hunk 2]
```diff
@@ -158,39 +159,72 @@ object UllmansAlgorithm {
...
+    // we try to find that cycle first and then check every other strong edge.
+    bfs(firstCheck.head, firstCheck.body) match {
+      case Some(pred) =>
+        // we found a cycle and can report it
+        val DependencyEdge.Strong(head, body, loc) = firstCheck
+        (body, loc) :: unroll(body, head, pred) ::: (body, loc) :: Nil
+      case None =>
+        // `firstCheck` is not a part of a cycle to we check the same
+        // for all strong edges.
+        // TODO: The strong cycle can reach `firstcheck.head` so we could
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/phase/UllmansAlgorithm.scala:213]: We tend to avoid TODOs in code, especially for less important things. Instead you should open a ticket! 

TODOs in code are forgotten. Less so for tickets.

File: main/src/ca/uwaterloo/flix/language/phase/UllmansAlgorithm.scala [hunk 3]
```diff
@@ -158,39 +159,72 @@ object UllmansAlgorithm {
...
+        //       only check edges that are reachable from `src` in the
+        //       transposed graph.
+        for (edge <- g) edge match {
+          case DependencyEdge.Weak(_, _, _) => ()
+          case DependencyEdge.Strong(head, body, loc) =>
+            bfs(head, body) match {
+              case Some(pred) =>
+                return (body, loc) :: unroll(body, head, pred) ::: (body, loc) :: Nil
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/phase/UllmansAlgorithm.scala:221]: Can the return statement by avoided with a more functional solution?

**Review by magnus-madsen — COMMENTED** [review]
Added a few comments, I will take a deeper look later.

File: main/src/ca/uwaterloo/flix/language/phase/UllmansAlgorithm.scala (hunk 1 above)
Comment (JonathanStarup) [reply main/src/ca/uwaterloo/flix/language/phase/UllmansAlgorithm.scala:120]: A `DependencyEdge.Strong` type is needed and edge is just of DependencyEdge type

Comment (magnus-madsen) [reply main/src/ca/uwaterloo/flix/language/phase/UllmansAlgorithm.scala:120]: OK
