### PR TITLE
Kinder

### LINKED ISSUE #999: Ensure Well-Kinded Types
A bit of background:

A type system ensures that ill-formed expressions such as:

```
if ("hello world") 123 else true
```

are rejected.

A kind system ensures that ill-formed types such as:

```
List[String, String]
Option[Pure]
Int -> 
{ x: Int, y: Int | Bool }
```

are rejected.

The purpose of this ticket is to ensure that the Flix compiler correctly enforces well-kinded types.

The starting point for this is to change `ast/Type.scala` such that fresh type variables always have the right kind. Specifically, inside Type there is:

`freshTypeVarXXXDeprecated` which should be replaced by calls to either:

- `freshTypeVar` if the type variable represents a proper type (kind Star).
- `freshTypeVarWithKind` passing the appropriate kind (e.g. for records, schemas, etc.)

(Right click-> Find usages in Intellij IDEA should be useful here).

Once this is done, `Unification.scala` lines 270 should enforce well-kindedness:

```scala
    def unifyVar(x: Type.Var, tpe: Type): Result[Substitution, UnificationError] = {
      // The type variable and type are in fact the same.
      if (x == tpe) {
        return Result.Ok(Substitution.empty)
      }

      // The type variable occurs inside the type.
      if (tpe.typeVars contains x) {
        return Result.Err(UnificationError.OccursCheck(x, tpe))
      }

      // HERE
      //if (x.kind != tpe.kind) {
      //  return Result.Err(TypeError.KindError())
      //}

      // We can substitute `x` for `tpe`. Update the textual name of `tpe`.
      if (x.getText.nonEmpty && tpe.isInstanceOf[Type.Var]) {
        tpe.asInstanceOf[Type.Var].setText(x.getText.get)
      }
      Result.Ok(Substitution.singleton(x, tpe))
    }
```

More background material can be found in:

- Types and Programming Languages (chapter 29: Type Operators and Kinding) - note the system here is more expressive than HM.
- Typing Haskell in Haskell (chapter 3 and onwards)
- https://en.wikipedia.org/wiki/Kind_(type_theory)

***I have created a branch named "issue-999-well-kinded" where this work should take place***

### LINKED ISSUE #1316: Enforce Kind Annotations for Type Variables of non-Star Kind?
For discussion:

Would it make sense for us to require that type variables of non-Star (i.e. for type variables that represent anything other than regular types) kind must be annotated?

We would still allow "normal" type definitions such as:

```
enum List[t] {
    case Nil,
    case Cons(t, List[t])
}
```

but if you do something like this:

```
enum Foo[a, b, e] {
  case Bar(a, a -> b & e)
}
```

you ***must*** now write:

```
enum Foo[a, b, e: Effect] { // discuss syntax
  case Bar(a, a -> b & e)
}
```

to *explicitly* state that e is of a non-star kind.

### LINKED ISSUE #1380: Enums with non-Star Kinds
For #1375, I want to write something like:
 
```
enum Choice[a, isAbsent, isPresent] {
    case Absent,
    case Present(a)
}

def some(x: a): Choice[a, false, _] = Present(x)
```

but:

image

Question is how to fix this. I might add that `Absent` and `Present` are like GADTs, so maybe:

```
enum Choice[a, isAbsent, isPresent] {
    case Absent: Choice[a, false, isPresent],
    case Present(a): Choice[a, isAbsent, false]
}
```

But, at this time, I really don't want to mess around too much with GADTs. I just need something like it for #1375.

### LINKED ISSUE #1637: Bug with type aliases
Bug identified by a user on Gitter: 

```
type alias Road[a] = {x: Int, y: Int | a }



/// Returns the area of the polymorphic record `r`.
/// Note that the use of the type variable `a` permits the record `r`
/// to have labels other than `x` and `y`.
def polyArea[a](r: Road[a]): Int = r.x * r.y

/// Computes the area of various rectangle records.
/// Note that some records have additional fields.
def polyAreas(): List[Int] =
    polyArea({x = 1, y = 2}) ::
    polyArea({x = 2, y = 3, z = 4}) :: Nil

def main(): List[Int] = polyAreas()
```

Causes
```
-- Type Error -------------------------------------------------- ???

>> The type scheme: '∀(a).{ x: Int32, y: Int32 | a } -> Int32' cannot be generalized to '∀(a).{ x: Int32, y: Int32 | a } -> Int32'.

8 | def polyArea[a](r: Road[a]): Int = r.x * r.y
        ^^^^^^^^
        unable to generalize the type scheme.

Possible fixes:

  (1) The function is declared as too polymorphic. Remove some type variables.
  (2) The expression body of the function is incorrect.
```

Might have something to do with the early kind inference?

### LINKED ISSUE #1766: Check for Mismatched Kinds
This program compiles, but should not (?):

```
lawless class A[t :# Bool] {
    pub def f(): t // this should probably *also* complain that the return type is uninhabited.
}

lawless class B[t] extends A[t] {
    pub def g(x: t): Bool
}
```

Note the kinds are different.

### LINKED ISSUE #1791: Syntactic Kind Inference
**Enums**: The following rules apply, either:
- All type variables are explicitly ascribed with a kind, *or*
- All type variables are assumed to be of kind `Star`.
- (It is illegal for only a subset of type variables to be ascribed.)
- (EDIT: Must check that kinds fit with their use within the enum).

**Type Aliases**: The following rules apply, either:
- All type variables are explicitly ascribed with a kind, *or*
- All type variables are assumed to be of kind `Star`.
- (It is illegal for only a subset of type variables to be ascribed.)
- (EDIT: Must check that kinds fit with their use within the enum).

**Type Classes**: The following rules apply, either:
- The single type variable is explicitly ascribed with a kind, *or*
- The single type variable is assumed to be of kind `Star`.
- (It is illegal for only a subset of type variables to be ascribed.)
- (EDIT: Must check that kinds fit with their use within the enum).

**Type Class Instances**: The following rules apply:
- The kinds are always derived from the kinds of the classes (Must happen after classes have been "kinded".)

**Defs**: The following rules apply, either:
- Explicit mode: All type variables are explicitly ascribed with a kind, *or*
- Implicit mode: The following syntactic rules apply. Given a type, recursively determine the type of every type variable:
  - If the type variable appears as an argument to an enum use its kind.
  - If the type variable appears as an argument to type alias use its kind.
  - If the type variable appears as an argument to type class use its kind.
  - Otherwise, consider:
    - If in a type position => type 
    - If in an effect position => boolean (e.g. on an arrow)
    - If in a record/schema position => record/schema
    - If in a Boolean position => boolean
  - If these constraints are inconsistent => error.

These rules are pretty inflexible, but they could be relaxed later.

What constructs am I missing? Laws?

Question: When should ill-kinded types be reported? During kind inference or in type inference?

### PR DESCRIPTION
**Pull request by mlutze**
Fixes #1791
Fixes #1766
Fixes #1637
Fixes #1380 
Fixes #1316 
Fixes #999 

### Features
* Def: bad effect kind
  * [x] impl
  * [x] test
* Def: bad kind inside expression
  * [x] impl
  * [x] test
* Def: bad kind inside type
  * [x] impl
  * [x] test
* Def: bad parameter kind
  * [x] impl
  * [x] test
* Def: bad return type kind
  * [x] impl
  * [x] test
* Def: bad type constraint kind
  * [x] impl
  * [x] test
* Def: infer kinds if unannotated
  * [x] impl
  * [x] test
* Def: mismatched inferred kinds
  * [x] impl
  * [x] test
* Enum: bad case parameter kind
  * [x] impl
  * [x] test
* Enum: bad kind inside type
  * [x] impl
  * [x] test
* Instance: bad kind inside def
  * [x] impl
  * [x] test
* Instance: bad type constraint kind
  * [x] impl
  * [x] test
* Instance: bad type parameter kind
  * [x] impl
  * [x] test
* Type alias: bad kind inside type
  * [x] impl
  * [x] test
* Type class: bad kind inside law
  * [x] impl
  * [x] test
* Type class: bad kind inside sig
  * [x] impl
  * [x] test
* Type class: bad type constraint kind
  * [x] impl
  * [x] test

### General requirements
* [x] Don't make a complete mess
* [x] Don't break anything else
* [x] Provide documentation
* [x] Add license to new files
* [x] Manually check new error formatting
* [x] Manually check diff

### Notes from discussion:
* All tvars in expressions have to be known from the type signature, so there's no need to infer anything from the expression.
* Would be nice to have two source locations for kind errors
* Ambiguous kind variables must be rejected. (i.e. if a the kind of a variable is under-determined).

### Some challenges and proposed solutions:
* Syntax like `x: {| a}` (indicating `x` is a variable with type `a`, where `a` has kind `Record`) gets erased by the time we get to the Kinder.
  * I'm thinking we turn this into syntactic sugar for a kind ascription, which I believe we wanted to support originally anyway
    * **DONE**
* Subkinding doesn't play nicely with kind unification.
  * Change the substitution somehow, so we have a collection of kvars pointing to a kind, then update the kind they point to if one of the kvars unifies with a subkind of whatever they were pointing to
    * **SIMPLIFIED KIND INFERENCE**
  * Eventually I think we need to get rid of subkinding.
* Type aliases are erased before getting to the Kinder
  * I think we can just carry these through one more phase and drop them after the Kinder.
    * **DONE**

### Follow up steps:
* `FormatUnkindedType`
* Improve location information on types

### CODE REVIEW

**Comment by mlutze** [comment]
!!!benchmark
So we have a baseline for comparison after the removal of all the slow monadic stuff.

**Comment by mlutze** [comment]
!!!benchmark
Definitions have been moved to the simpler kind inference model, so we should see some speedups compared to last time.

File: main/src/ca/uwaterloo/flix/language/phase/Kinder.scala [hunk 1]
```diff
@@ -0,0 +1,1077 @@
...
+  * Attributes kinds to the types in the AST.
+  *
+  * For enums, classes, instances, and type aliases,
+  * kinds are either explicit or assumed to be Star.
+  *
+  * For defs,
+  * kinds are either explicit or are inferred from their
+  * use in the formal parameters, return type and effect, and type constraints.
+  *
+  * In inferring types, variable type constructors are assumed to have kind * -> * -> * -> ???.
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:36]: Could we add the rules from the ticket here? and update them with the latest developments?

**Review by magnus-madsen — COMMENTED** [review]
I added some comments. Still not done :)

File: main/src/ca/uwaterloo/flix/language/errors/KindError.scala [hunk 2]
```diff
@@ -0,0 +1,75 @@
...
+    * @param k2   the second kind.
+    * @param loc the location where the error occurred.
+    */
+  case class MismatchedKinds(k1: Kind, k2: Kind, loc: SourceLocation) extends KindError {
+    override def summary: String = s"Mismatched kinds: '${formatKind(k1)}' and '${formatKind(k2)}''"
+
+    override def message: VirtualTerminal = {
+      val vt = new VirtualTerminal()
+      vt << Line(kind, source.format) << NewLine
+      vt << ">> This type variable was used as both kind '" << Red(formatKind(k1)) << "' and kind '" << Red(formatKind(k2)) << "'." << NewLine
```
[the remark this answers is not in the document]
Comment (mlutze) [reply main/src/ca/uwaterloo/flix/language/errors/KindError.scala:45]: Screenshot from 2021-08-02 16-26-31

File: main/src/ca/uwaterloo/flix/language/errors/KindError.scala [hunk 3]
```diff
@@ -0,0 +1,75 @@
...
+
+  /**
+    * An error describing a kind that doesn't match the expected kind.
+    *
+    * @param expectedKind the expected kind.
+    * @param actualKind   the actual kind.
+    * @param loc          the location where the error occurred.
+    */
+  case class UnexpectedKind(expectedKind: Kind, actualKind: Kind, loc: SourceLocation) extends KindError {
+    override def summary: String = s"Kind ${formatKind(actualKind)} found where kind ${formatKind(actualKind)} was expected."
```
[the remark this answers is not in the document]
Comment (mlutze) [reply main/src/ca/uwaterloo/flix/language/errors/KindError.scala:62]: This is the one where locations are quite bad.

One nice example:
Screenshot from 2021-08-02 16-33-01

Some not-so-nice examples:
Screenshot from 2021-08-02 16-34-18
Screenshot from 2021-08-02 16-34-43

File: main/src/ca/uwaterloo/flix/language/ast/Symbol.scala [hunk 4]
```diff
@@ -70,21 +70,21 @@ object Symbol {
     * Returns a fresh variable symbol for the given identifier.
     */
   def freshVarSym(ident: Name.Ident)(implicit flix: Flix): VarSym = {
-    new VarSym(flix.genSym.freshId(), ident.name, Type.freshVar(Kind.Star), Scopedness.Unscoped, ident.loc)
+    new VarSym(flix.genSym.freshId(), ident.name, UnkindedType.freshVar(loc = ident.loc), Scopedness.Unscoped, ident.loc)
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/ast/Symbol.scala:73]: I wonder if its a problem that symbols carry unkinded types. This means that later we cannot rely on a symbol for its kind?

Comment (magnus-madsen) [reply main/src/ca/uwaterloo/flix/language/ast/Symbol.scala:73]: After discussion- let us add a comement that var symbols are always of kind Star.

File: main/src/ca/uwaterloo/flix/language/ast/UnkindedType.scala [hunk 5]
```diff
@@ -0,0 +1,595 @@
...
+  */
+sealed trait UnkindedType {
+
+  /**
+    * Returns the type constructor of the given type.
+    */
+  def typeConstructor: Option[UnkindedType.Constructor] = this match {
+    case UnkindedType.Cst(cst, _) => Some(cst)
+    case UnkindedType.Apply(t1, _) => t1.typeConstructor
+    case UnkindedType.Lambda(_, _) => throw InternalCompilerException("Unexpected type constructor: Lambda")
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/ast/UnkindedType.scala:32]: We usually move the exception cases to the end of the match (in other phases we do this a lot)

File: main/test/ca/uwaterloo/flix/language/phase/TestKinder.scala [hunk 6]
```diff
@@ -0,0 +1,783 @@
...
+import ca.uwaterloo.flix.TestUtils
+import ca.uwaterloo.flix.language.errors.KindError
+import ca.uwaterloo.flix.util.Options
+import org.scalatest.FunSuite
+
+class TestKinder extends FunSuite with TestUtils {
+
+  private val DefaultOptions = Options.TestWithLibNix
+
+  ////// TESTS COPIED FROM OTHER PHASES //////
```
Comment (magnus-madsen) [inline main/test/ca/uwaterloo/flix/language/phase/TestKinder.scala:27]: OK, and comment can be removed :)

File: main/test/ca/uwaterloo/flix/language/phase/TestKinder.scala [hunk 7]
```diff
@@ -0,0 +1,783 @@
...
+    expectError[KindError](result)
+  }
+
+  test("IllegalTypeApplication.08") {
+    val input = "def f(a: (Int, true)): Int = 1"
+    val result = compile(input, DefaultOptions)
+    expectError[KindError](result)
+  }
+
+  ////// NEW TESTS START HERE //////
```
Comment (magnus-madsen) [inline main/test/ca/uwaterloo/flix/language/phase/TestKinder.scala:404]: And this comment can be removed too :)

File: main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala [hunk 8]
```diff
@@ -372,7 +386,19 @@ object NamedAst {
 
   case class SelectChannelRule(sym: Symbol.VarSym, chan: NamedAst.Expression, exp: NamedAst.Expression)
 
-  case class TypeParam(name: Name.Ident, tpe: ast.Type.Var, loc: SourceLocation)
+  sealed trait TypeParam {
+    val name: Name.Ident
+    val tpe: ast.UnkindedType.Var
+    val loc: SourceLocation
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala:392]: these should be defs instead of vals.

File: main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala [hunk 9]
```diff
@@ -372,7 +386,19 @@ object NamedAst {
...
+  }
+
+  object TypeParam {
+
+    case class Kinded(name: Name.Ident, tpe: ast.UnkindedType.Var, kind: Kind, loc: SourceLocation) extends TypeParam
+
+    case class Unkinded(name: Name.Ident, tpe: ast.UnkindedType.Var, loc: SourceLocation) extends TypeParam
+
+  }
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/ast/NamedAst.scala:401]: I like the design with TypeParam and TypeParams 👍

**Review by magnus-madsen — COMMENTED** [review]
Still working my way through. So far nothing major.

File: main/src/ca/uwaterloo/flix/language/phase/Kinder.scala [hunk 10]
```diff
@@ -0,0 +1,1077 @@
...
+        defsVal = Validation.traverse(defs0)(visitDef(_, kinds, root))
+        result <- Validation.sequenceT(tpeVal, tconstrsVal, defsVal)
+        (tpe, tconstrs, defs) = result
+      } yield KindedAst.Instance(doc, mod, sym, tpe, tconstrs, defs, ns, loc)
+  }
+
+  /**
+    * Gets the kind of the enum.
+    */
+  def getEnumKind(enum: ResolvedAst.Enum)(implicit flix: Flix): Kind = enum match {
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:264]: private

File: main/src/ca/uwaterloo/flix/language/phase/Kinder.scala [hunk 11]
```diff
@@ -0,0 +1,1077 @@
...
+      val kenv = getKindsFromTparamsDefaultStar(tparams)
+      tparams.tparams.foldRight(Kind.Star: Kind) {
+        case (tparam, acc) => kenv.map(tparam.tpe) ->: acc
+      }
+  }
+
+  /**
+    * Gets the kind of the class.
+    */
+  def getClassKind(clazz: ResolvedAst.Class): Kind = clazz.tparam match {
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:275]: private

File: main/src/ca/uwaterloo/flix/language/phase/Kinder.scala [hunk 12]
```diff
@@ -0,0 +1,1077 @@
...
+  }
+
+
+  /**
+    * Performs kinding on the given def under the given kind environment.
+    */
+  private def visitDef(def0: ResolvedAst.Def, kinds0: KindEnv, root: ResolvedAst.Root)(implicit flix: Flix): Validation[KindedAst.Def, KindError] = def0 match {
+    case ResolvedAst.Def(sym, spec0, exp0) =>
+      for {
+        specKinds <- getKindsFromSpec(spec0, root)
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:330]: specKinds -> kindEnv?

File: main/src/ca/uwaterloo/flix/language/phase/Kinder.scala [hunk 13]
```diff
@@ -0,0 +1,1077 @@
...
+      } yield KindedAst.Def(sym, spec, exp)
+  }
+
+  /**
+    * Performs kinding on the given sig under the given kind environment.
+    */
+  private def visitSig(sig0: ResolvedAst.Sig, kenv0: KindEnv, root: ResolvedAst.Root)(implicit flix: Flix): Validation[KindedAst.Sig, KindError] = sig0 match {
+    case ResolvedAst.Sig(sym, spec0, exp0) =>
+      for {
+        specKinds <- getKindsFromSpec(spec0, root)
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:343]: specKinds -> kindEnv?

File: main/src/ca/uwaterloo/flix/language/phase/Kinder.scala [hunk 14]
```diff
@@ -0,0 +1,1077 @@
...
+  }
+
+  /**
+    * Performs kinding on the given expression under the given kind environment.
+    */
+  private def ascribeExpression(exp00: ResolvedAst.Expression, kenv: KindEnv, root: ResolvedAst.Root)(implicit flix: Flix): Validation[KindedAst.Expression, KindError] = exp00 match {
+    case ResolvedAst.Expression.Wild(loc) => KindedAst.Expression.Wild(Type.freshVar(Kind.Star), loc).toSuccess
+    case ResolvedAst.Expression.Var(sym, tpe0, loc) =>
+      mapN(ascribeType(tpe0, KindMatch.subKindOf(Kind.Star), kenv, root)) {
+        tpe => KindedAst.Expression.Var(sym, tpe, loc)
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:395]: So, do we have some tests like:

```
def foo(): Int32 & ef = 
  let x: Option[ef] = ...
```

Or similar? For the Var case and for Let/Ascribe?

File: main/src/ca/uwaterloo/flix/language/phase/Kinder.scala [hunk 15]
```diff
@@ -0,0 +1,1077 @@
...
+    case ResolvedAst.Expression.Str(lit, loc) => KindedAst.Expression.Str(lit, loc).toSuccess
+    case ResolvedAst.Expression.Default(loc) => KindedAst.Expression.Default(Type.freshVar(Kind.Star), loc).toSuccess
+    case ResolvedAst.Expression.Apply(exp0, exps0, loc) =>
+      for {
+        exp <- ascribeExpression(exp0, kenv, root)
+        exps <- Validation.traverse(exps0)(ascribeExpression(_, kenv, root))
+      } yield KindedAst.Expression.Apply(exp, exps, Type.freshVar(Kind.Star), Type.freshVar(Kind.Bool), loc)
+    case ResolvedAst.Expression.Lambda(fparam0, exp0, loc) =>
+      for {
+        fparam <- ascribeFormalParam(fparam0, kenv, root)
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:421]: I am ok with calling it `ascribeX`, but in most other phases we simply call the main recursive traversal for `visit`. Is it better to be precise?

File: main/src/ca/uwaterloo/flix/language/phase/Kinder.scala [hunk 16]
```diff
@@ -0,0 +1,1077 @@
...
+        exp <- ascribeExpression(exp0, kenv, root)
+      } yield KindedAst.Expression.Lambda(fparam, exp, Type.freshVar(Kind.Star), loc)
+    case ResolvedAst.Expression.Unary(sop, exp0, loc) =>
+      for {
+        exp <- ascribeExpression(exp0, kenv, root)
+      } yield KindedAst.Expression.Unary(sop, exp, Type.freshVar(Kind.Star), loc)
+    case ResolvedAst.Expression.Binary(sop, exp10, exp20,  loc) =>
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:428]: exp10, exp20? What? o_O

File: main/src/ca/uwaterloo/flix/language/phase/Kinder.scala [hunk 17]
```diff
@@ -0,0 +1,1077 @@
...
+    case ResolvedAst.Expression.PutStaticField(field, exp0, loc) =>
+      for {
+        exp <- ascribeExpression(exp0, kenv, root)
+      } yield KindedAst.Expression.PutStaticField(field, exp, loc)
+    case ResolvedAst.Expression.NewChannel(exp0, tpe0, loc) =>
+      for {
+        exp <- ascribeExpression(exp0, kenv, root)
+        tpe <- ascribeType(tpe0, KindMatch.subKindOf(Kind.Star), kenv, root)
+      } yield KindedAst.Expression.NewChannel(exp, tpe, loc)
+    case ResolvedAst.Expression.GetChannel(exp0, loc) =>
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:603]: Could you add a line break between every case. I think we usually do that to have some visual separation. Makes it easier to find a specific case.

File: main/src/ca/uwaterloo/flix/language/phase/Kinder.scala [hunk 18]
```diff
@@ -0,0 +1,1077 @@
...
+  }
+
+  private object KindMatch {
+
+
+    /**
+      * A KindMatch that matches every kind.
+      */
+    // association doesn't matter
+    val wild: KindMatch = KindMatch(Association.SubKind, Kind.Wild)
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:1011]: Constants are usually Uppercase.

File: main/src/ca/uwaterloo/flix/language/phase/Kinder.scala [hunk 19]
```diff
@@ -0,0 +1,1077 @@
...
+  def getClassKind(clazz: ResolvedAst.Class): Kind = clazz.tparam match {
+    case ResolvedAst.TypeParam.Kinded(_, _, kind, _) => kind
+    case _: ResolvedAst.TypeParam.Unkinded => Kind.Star
+  }
+
+
+  /**
+    * Performs kinding on the given type constructor under the given kind environment.
+    */
+  def ascribeTypeConstructor(tycon: UnkindedType.Constructor, root: ResolvedAst.Root)(implicit flix: Flix): TypeConstructor = tycon match {
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:284]: I think this helper function should go near the bottom, next to its friend.

File: main/src/ca/uwaterloo/flix/language/phase/Kinder.scala (hunk 11 above)
Comment (magnus-madsen) [reply main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:275]: and move to bottom. (Unless it is only used here.)

File: main/src/ca/uwaterloo/flix/language/phase/Kinder.scala [hunk 20]
```diff
@@ -0,0 +1,1077 @@
...
+    case ResolvedAst.Annotation(name, exps0, loc) =>
+      mapN(Validation.traverse(exps0)(ascribeExpression(_, kinds, root))) {
+        exps => KindedAst.Annotation(name, exps, loc)
+      }
+  }
+
+  /**
+    * Performs kinding on the given expression under the given kind environment.
+    */
+  private def ascribeExpression(exp00: ResolvedAst.Expression, kenv: KindEnv, root: ResolvedAst.Root)(implicit flix: Flix): Validation[KindedAst.Expression, KindError] = exp00 match {
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:391]: Very very approximately most phase are structured like:

- def stuff
- expression stuff
- pattern stuff
- type stuff
- helper functions

I think we can do the same here.

File: main/src/ca/uwaterloo/flix/language/phase/Kinder.scala [hunk 21]
```diff
@@ -0,0 +1,1077 @@
...
+        cparams <- Validation.traverse(cparams0)(ascribeCparam(_, kenv, root))
+        head <- ascribeHeadPredicate(head0, kenv, root)
+        body <- Validation.traverse(body0)(ascribeBodyPredicate(_, kenv, root))
+      } yield KindedAst.Constraint(cparams, head, body, loc)
+  }
+
+  /**
+    * Performs kinding on the given constraint param under the given kind environment.
+    */
+  private def ascribeCparam(cparam0: ResolvedAst.ConstraintParam, kenv: KindEnv, root: ResolvedAst.Root): Validation[KindedAst.ConstraintParam, KindError] = cparam0 match {
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:773]: In function names we dont shorten to fparam or cparam. Its usually `visitFormalParam` etc.

File: main/src/ca/uwaterloo/flix/language/phase/Kinder.scala [hunk 22]
```diff
@@ -0,0 +1,1077 @@
...
+  private def inferTconstr(tconstr: ResolvedAst.TypeConstraint, root: ResolvedAst.Root)(implicit flix: Flix): Validation[KindEnv, KindError] = tconstr match {
+    case ResolvedAst.TypeConstraint(clazz, tpe, loc) =>
+      val kind = getClassKind(root.classes(clazz))
+      inferType(tpe, KindMatch.subKindOf(kind), root)
+  }
+
+  /**
+    * Infers a kind environment from the given type, with an expectation from context.
+    */
+  private def inferType(tpe: UnkindedType, expectedType: KindMatch, root: ResolvedAst.Root)(implicit flix: Flix): Validation[KindEnv, KindError] = tpe.baseType match {
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:853]: Whats the difference between the ascribeX and inferX? I think its that one translates and the other gives back a kind env.

File: main/src/ca/uwaterloo/flix/language/phase/Kinder.scala [hunk 23]
```diff
@@ -0,0 +1,1077 @@
...
+
+    def superKindOf(kind: Kind): KindMatch = KindMatch(Association.SuperKind, kind)
+
+    /**
+      * Describes whether the KindMatch is a lower or upper bound.
+      */
+    sealed trait Association
+
+    object Association {
+      case object SubKind extends Association
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:1023]: So this is because of our incorrect representation of records/schemas?

File: main/src/ca/uwaterloo/flix/language/phase/Kinder.scala [hunk 24]
```diff
@@ -0,0 +1,1077 @@
...
+        exps => KindedAst.Annotation(name, exps, loc)
+      }
+  }
+
+  /**
+    * Performs kinding on the given expression under the given kind environment.
+    */
+  private def ascribeExpression(exp00: ResolvedAst.Expression, kenv: KindEnv, root: ResolvedAst.Root)(implicit flix: Flix): Validation[KindedAst.Expression, KindError] = exp00 match {
+    case ResolvedAst.Expression.Wild(loc) => KindedAst.Expression.Wild(Type.freshVar(Kind.Star), loc).toSuccess
+    case ResolvedAst.Expression.Var(sym, tpe0, loc) =>
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:393]: tpe0 here is really a tvar, right?

Comment (magnus-madsen) [reply main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:393]: Actually, why is there a tpe here? Isnt sym.tvar enough?

File: main/src/ca/uwaterloo/flix/language/phase/Kinder.scala [hunk 25]
```diff
@@ -0,0 +1,1077 @@
...
+    case UnkindedType.Cst(cst, loc) =>
+      val tyconKind = getTyconKind(cst, root)
+      val args = Kind.args(tyconKind)
+
+      Validation.fold(tpe.typeArguments.zip(args), KindEnv.empty) {
+        case (acc, (targ, kind)) => flatMapN(inferType(targ, KindMatch.subKindOf(kind), root)) {
+          kenv => acc ++ kenv
+        }
+      }
+    case UnkindedType.Apply(_, _) => throw InternalCompilerException("Unexpected type application.")
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:874]: Oooh okay. Why is this safe here? Also Exceptions are usually handled at the bottom.

**Review by magnus-madsen — COMMENTED** [review]
I finished my pass. Feel free to make changes now :)

File: main/src/ca/uwaterloo/flix/language/phase/Kinder.scala (hunk 15 above)
Comment (mlutze) [reply main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:421]: This is mostly an artifact from when more inference was going on: I had to distinguish between ascribing and inferring. I can change to `visit`.

File: main/src/ca/uwaterloo/flix/language/phase/Kinder.scala (hunk 16 above)
Comment (mlutze) [reply main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:428]: I semi-automated some of the repetitive parts. One of the "rules" I use is that "original" values that change when going to the next AST are named as `xxx0`. This gets a little ugly when `xxx` ends with a digit.

File: main/src/ca/uwaterloo/flix/language/phase/Kinder.scala (hunk 22 above)
Comment (mlutze) [reply main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:853]: Yes, that's about right. `inferX` builds a kind environment and `ascribeX` uses the kind environment to ascribe kinds to the types.

File: main/src/ca/uwaterloo/flix/language/phase/Kinder.scala (hunk 23 above)
Comment (mlutze) [reply main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:1023]: Yes, since there ends up being contravariance in the kinding of type lambdas, we have to be able to check both subkinding and superkinding.

File: main/src/ca/uwaterloo/flix/language/phase/Kinder.scala (hunk 25 above)
Comment (mlutze) [reply main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:874]: This is safe because of the definition of `UnkindedType.baseType`: on an `Apply` it just recurses. I guess I could enforce this in the type system with a union trait.

File: main/src/ca/uwaterloo/flix/language/phase/Kinder.scala (hunk 24 above)
Comment (mlutze) [reply main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:395]: The Resolver looks this type up in the type environment, so it could end up being a non-var. But does that duplicate the behavior of the Typer? I'll do some testing.

**Comment by magnus-madsen** [comment]
Ping me when I should do the next pass :)

File: main/src/ca/uwaterloo/flix/language/errors/KindError.scala [hunk 26]
```diff
@@ -0,0 +1,75 @@
...
+
+    override def message: VirtualTerminal = {
+      val vt = new VirtualTerminal()
+      vt << Line(kind, source.format) << NewLine
+      vt << ">> This type has kind '" << Red(formatKind(actualKind)) << "', but is used where kind '" << Red(formatKind(expectedKind)) << "' is expected." << NewLine
```
[the remark this answers is not in the document]
Comment (mlutze) [reply main/src/ca/uwaterloo/flix/language/errors/KindError.scala:67]: > we often pass these arguments as "actual", "expected". Both for the case class and in the error message.

> Reverse order

Here I have `$actual ... $expected`. At least one of us is confused.

File: main/src/ca/uwaterloo/flix/language/phase/Kinder.scala (hunk 24 above)
Comment (mlutze) [reply main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:395]: Stuff broke when I tried some naive changes to remove the tpe, so I suggest we keep it at least for now.

**Comment by mlutze** [comment]
@magnus-madsen RFR assuming the tests pass

File: main/src/ca/uwaterloo/flix/language/ast/Kind.scala [hunk 27]
```diff
@@ -119,8 +120,32 @@ object Kind {
...
+  def base(k: Kind): Kind = k match {
+    case Arrow(k1, _) => base(k1)
+    case _ => k
+  }
+
+  /**
+    * Returns the arguments of an arrow kind.
     */
-  def freshVar()(implicit flix: Flix): Kind = Var(flix.genSym.freshId())
+  def args(k: Kind): List[Kind] = k match {
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/ast/Kind.scala:134]: In `Type` this is called `typeArgs`, maybe we should call it `kindArgs` for consistency.

File: main/src/ca/uwaterloo/flix/language/ast/Kind.scala [hunk 28]
```diff
@@ -68,9 +69,9 @@ sealed trait Kind {
 object Kind {
 
   /**
-    * Represents a kind variable.
+    * Represents a wild kind.
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/ast/Kind.scala:72]: Lets a description: It is a kind that has not yet been determined, but will be determined and replaced by the Kinder.

Comment (magnus-madsen) [reply main/src/ca/uwaterloo/flix/language/ast/Kind.scala:72]: Right?

File: main/src/ca/uwaterloo/flix/language/ast/UnkindedType.scala [hunk 29]
```diff
@@ -0,0 +1,601 @@
...
+    case _ => Nil
+  }
+}
+
+object UnkindedType {
+
+  /**
+    * The union of non-Apply types.
+    */
+  sealed trait BaseType
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/ast/UnkindedType.scala:60]: Whats this used for? We don't have that in other places, right?

File: main/src/ca/uwaterloo/flix/language/ast/UnkindedType.scala [hunk 30]
```diff
@@ -0,0 +1,601 @@
...
+    * Type variable.
+    */
+  case class Var(id: Int, text: Option[String] = None, loc: SourceLocation) extends UnkindedType with BaseType {
+    /**
+      * Converts the UnkindedType to a Type with the given `kind`.
+      */
+    def ascribedWith(kind: Kind): Type.Var = Type.Var(id, kind, text = text)
+
+    override def equals(other: Any): Boolean = other match {
+      case Var(otherId, _, _) => id == otherId
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/ast/UnkindedType.scala:87]: I am surprised. This pattern match is not exhaustive, yet the code compiles?????????????????????????????

File: main/src/ca/uwaterloo/flix/language/ast/UnkindedType.scala [hunk 31]
```diff
@@ -0,0 +1,601 @@
...
+    /**
+      * A type constructor that represents the type of regions.
+      */
+    case object Region extends Constructor
+
+    val Pure: Constructor = True
+    val Impure: Constructor = False
+
+  }
+}
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/ast/UnkindedType.scala:601]: Not to go crazy, but the whole existence of UnkindedAst is because we want UnkindedType, right?

And the whole existence of UnkindedType is because a single type constructor (Var) cannot have a kind field?

Comment (magnus-madsen) [reply main/src/ca/uwaterloo/flix/language/ast/UnkindedType.scala:601]: If we changed `Type` to have `UnkindedVar(...)` and then had an invariant that this does not exist after the Kinder, would everything still work?

Comment (magnus-madsen) [reply main/src/ca/uwaterloo/flix/language/ast/UnkindedType.scala:601]: If this loss of type safety is too much, we could probably even use GADTs-- but that would come with its own challenges and probably not be worth it...

Comment (magnus-madsen) [reply main/src/ca/uwaterloo/flix/language/ast/UnkindedType.scala:601]: Lets talk :)

Comment (magnus-madsen) [reply main/src/ca/uwaterloo/flix/language/ast/UnkindedType.scala:601]: Giving up `sealed`, we could also introduce `UnkindedType` as a sub-type of Type with an extra case. We would then have to adapt certain function signatures.

File: main/src/ca/uwaterloo/flix/language/phase/Kinder.scala [hunk 32]
```diff
@@ -0,0 +1,1155 @@
...
+  *       - If the type variable is the type of a formal parameter, it is ascribed kind Star.
+  *       - If the type variable is the return type of the function, it is ascribed kind Star.
+  *       - If the type variable is the effect type of the function, it is ascribed kind Bool.
+  *       - If the type variable is an argument to a type constraint, it is ascribed the class's parameter kind
+  *       - If the type variable is an argument to a type constructor, it is ascribed the type constructor's parameter kind.
+  *       - If the type variable is used as an type constructor, it is ascribed the kind Star -> Star ... -> Star -> X,
+  *         where X is the kind inferred from enacting these rules in the place of the fully-applied type.
+  *       - If there is an inconsistency among these kinds, an error is raised.
+  *
+  * In inferring types, variable type constructors are assumed to have kind * -> * -> * -> ???.
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:49]: I don't understand.

File: main/src/ca/uwaterloo/flix/language/phase/Kinder.scala [hunk 33]
```diff
@@ -0,0 +1,1155 @@
...
+import ca.uwaterloo.flix.api.Flix
+import ca.uwaterloo.flix.language.CompilationError
+import ca.uwaterloo.flix.language.ast._
+import ca.uwaterloo.flix.language.errors.KindError
+import ca.uwaterloo.flix.util.Validation
+import ca.uwaterloo.flix.util.Validation.{ToFailure, ToSuccess, flatMapN, mapN, traverse}
+
+/**
+  * Attributes kinds to the types in the AST.
+  *
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:28]: What about non-enum, non-defs? E.g. type aliases? classes?

**Comment by magnus-madsen** [comment]
@stephentetley Heads-up: When this is merged soonish, we should have correct kinding. This may break incorrect code that was previously erroneously accepted by the compiler.

File: main/src/ca/uwaterloo/flix/language/phase/Kinder.scala [hunk 34]
```diff
@@ -0,0 +1,1155 @@
...
+  }
+
+  /**
+    * Performs kinding on the given def under the given kind environment.
+    */
+  private def visitDef(def0: ResolvedAst.Def, kenv0: KindEnv, root: ResolvedAst.Root)(implicit flix: Flix): Validation[KindedAst.Def, KindError] = def0 match {
+    case ResolvedAst.Def(sym, spec0, exp0) =>
+      for {
+        specKenv <- getKindEnvFromSpec(spec0, root)
+        kenv <- kenv0 ++ specKenv
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:171]: Are kenv0 and specKenv disjoint? My guess is yes.

File: main/src/ca/uwaterloo/flix/language/phase/Kinder.scala (hunk 24 above)
Comment (magnus-madsen) [reply main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:215]: Spooky

File: main/src/ca/uwaterloo/flix/language/phase/Kinder.scala [hunk 35]
```diff
@@ -0,0 +1,1155 @@
...
+      for {
+        exp <- visitExpression(exp0, kenv, root)
+      } yield KindedAst.Expression.RecordSelect(exp, field, Type.freshVar(Kind.Star), loc)
+
+    case ResolvedAst.Expression.RecordExtend(field, value0, rest0, loc) =>
+      // Ideally, if `rest` is not of record kind, we should throw a kind error.
+      // But because we have subkinding, we can't do this in the Kinder.
+      // Consider: { +name = 5 | id({}) }
+      // This is OK, but would be seen as a kind error since id is `(a: *) -> (a: *)`, so `id({}) :: *`
+      // This KindError will be caught later in the Typer
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:335]: Do we have a path towards correct kinding for records/schemas? (This is completely swapped out of my mind.)

File: main/src/ca/uwaterloo/flix/language/phase/Kinder.scala [hunk 36]
```diff
@@ -0,0 +1,1155 @@
...
+    case ResolvedAst.Predicate.Body.Guard(exp0, loc) =>
+      for {
+        exp <- visitExpression(exp0, kenv, root)
+      } yield KindedAst.Predicate.Body.Guard(exp, loc)
+  }
+
+  /**
+    * Performs kinding on the given type variable under the given kind environment, with `kindMatch` expected from context.
+    */
+  private def visitTypeVar(tvar: UnkindedType.Var, kindMatch: KindMatch, kenv: KindEnv): Validation[Type.Var, KindError] = tvar match {
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:695]: 👍

File: main/src/ca/uwaterloo/flix/language/phase/Kinder.scala [hunk 37]
```diff
@@ -0,0 +1,1155 @@
...
+    case tvar: UnkindedType.Var => visitTypeVar(tvar, expectedKind, kenv)
+    case UnkindedType.Cst(cst, loc) =>
+      val tycon = visitTypeConstructor(cst, root)
+      val kind = tycon.kind
+      if (expectedKind.matches(kind)) {
+        Type.Cst(tycon, loc).toSuccess
+      } else {
+        KindError.UnexpectedKind(expectedKind = expectedKind.kind, actualKind = kind, loc).toFailure
+      }
+    case UnkindedType.Apply(t10, t20) =>
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:734]: Whats with the t10 and t20 again :)

File: main/src/ca/uwaterloo/flix/language/phase/Kinder.scala [hunk 38]
```diff
@@ -0,0 +1,1155 @@
...
+    * Performs kinding on the given free type variable, with `kindMatch` expected from context.
+    */
+  private def visitFreeTypeVar(tvar: UnkindedType.Var, kindMatch: KindMatch): Type.Var = tvar match {
+    case UnkindedType.Var(id, text, loc) =>
+      val kind = kindMatch.kind
+      Type.Var(id, kind, text = text)
+  }
+
+  /**
+    * Performs kinding on the given type under the given kind environment, with `kindMatch` expected from context.
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:722]: Could we add one more sentence of explaination. I assume this essentially "type checking the kind" recursively.

File: main/src/ca/uwaterloo/flix/language/phase/Kinder.scala [hunk 39]
```diff
@@ -0,0 +1,1155 @@
...
+    * Infers a kind environment from the given type constraint.
+    */
+  private def inferTconstr(tconstr: ResolvedAst.TypeConstraint, root: ResolvedAst.Root)(implicit flix: Flix): Validation[KindEnv, KindError] = tconstr match {
+    case ResolvedAst.TypeConstraint(clazz, tpe, loc) =>
+      val kind = getClassKind(root.classes(clazz))
+      inferType(tpe, KindMatch.subKindOf(kind), root)
+  }
+
+  /**
+    * Infers a kind environment from the given type, with an expectation from context.
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:913]: I also request one line more of doc

File: main/src/ca/uwaterloo/flix/language/ast/Kind.scala (hunk 28 above)
Comment (mlutze) [reply main/src/ca/uwaterloo/flix/language/ast/Kind.scala:72]: I think some Wild kinds can escape to later phases, but only if they are somehow irrelevant. E.g. if we have (`def f(x: m[_]): Int = ???`, the underscore might have kind `Wild`.

File: main/src/ca/uwaterloo/flix/language/ast/UnkindedType.scala (hunk 29 above)
Comment (mlutze) [reply main/src/ca/uwaterloo/flix/language/ast/UnkindedType.scala:60]: This was to get rid of the `InternalCompilerException` case on using the output of `UnkindedType.baseType`. We don't have this in `Type.scala`

Comment (magnus-madsen) [reply main/src/ca/uwaterloo/flix/language/ast/UnkindedType.scala:60]: OK; a comment would be useful. Should we also have it in Type?

File: main/src/ca/uwaterloo/flix/language/ast/UnkindedType.scala (hunk 30 above)
Comment (mlutze) [reply main/src/ca/uwaterloo/flix/language/ast/UnkindedType.scala:87]: Yes, very weird...

File: main/src/ca/uwaterloo/flix/language/phase/Kinder.scala (hunk 32 above)
Comment (mlutze) [reply main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:49]: Did you understand the rule:
```
  *       - If the type variable is used as an type constructor, it is ascribed the kind Star -> Star ... -> Star -> X,
  *         where X is the kind inferred from enacting these rules in the place of the fully-applied type.
```
?

This is a worse explanation of the same rule that I forgot to remove :)

File: main/src/ca/uwaterloo/flix/language/ast/UnkindedType.scala (hunk 29 above)
Comment (mlutze) [reply main/src/ca/uwaterloo/flix/language/ast/UnkindedType.scala:60]: `Type.scala` doesn't have this function.

File: main/src/ca/uwaterloo/flix/language/phase/Kinder.scala (hunk 35 above)
Comment (mlutze) [reply main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:335]: The latest ideas on that front are here: https://github.com/flix/flix/issues/2057

File: main/src/ca/uwaterloo/flix/language/phase/Kinder.scala (hunk 33 above)
Comment (mlutze) [reply main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:28]: Can you elaborate? Enums, classes, instances, type aliases are bundled under the first rule group since their rules are essentially equivalent.

File: main/src/ca/uwaterloo/flix/language/phase/Kinder.scala (hunk 34 above)
Comment (mlutze) [reply main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:171]: Yes. `kenv0` should only contain tparams from an instance type, which would then not be present in a def's spec.

File: main/src/ca/uwaterloo/flix/language/phase/Kinder.scala (hunk 37 above)
Comment (mlutze) [reply main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:734]: is `t1_0` a better naming convention? I wanted to keep things consistent (and easy to automate) with the `0` suffix.

File: main/src/ca/uwaterloo/flix/language/phase/Kinder.scala (hunk 33 above)
Comment (magnus-madsen) [reply main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:28]: Ah yes, but the documentation does not say that. Does it?

Comment (mlutze) [reply main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:28]: Line 29 mentions it. Were you looking for something more?

Comment (magnus-madsen) [reply main/src/ca/uwaterloo/flix/language/phase/Kinder.scala:28]: My bad!

**Comment by stephentetley** [comment]
> 
> 
> @stephentetley Heads-up: When this is merged soonish, we should have correct kinding. This may break incorrect code that was previously erroneously accepted by the compiler.

Thanks for the heads up, Magnus. This shouldn't be a problem.

**Comment by magnus-madsen** [comment]
This is about ready to wrap up right? Just missing some tests and few minor things?

**Comment by mlutze** [comment]
Yes, working on a comprehensive test suite.

**Comment by magnus-madsen** [comment]
> 
> 
> Yes, working on a comprehensive test suite.

OK, hopefully not too comprehensive. I am ok with 1000 loc of tests, but not 2k or 5k lines of auto-generated tests :)

**Comment by magnus-madsen** [comment]
Merged! Awesome :)
