### PR TITLE
feat: Fix parser crash on bad match case

### LINKED ISSUE #7646: Parser: is stuck
```
instance ToString[Card] {
    pub def toString(x: Card): String = match x {
        case Card.Card(r, s) _ => "${r} of ${s}"
    }
}
```

### PR DESCRIPTION
**Pull request by herluf-ba**
Closes #7646 

The example now gives 3 parser errors:
```
-- Parse Error -------------------------------------------------- main/foo.flix

>> Parse Error: Expected '=>' before '_'

3 |         case Card.Card(r, s) _ => "${r} of ${s}"
                               ^
                               Here
Syntactic Context: OtherExpr.

-- Parse Error -------------------------------------------------- main/foo.flix

>> Parse Error: Expected '}' before '=>'

3 |         case Card.Card(r, s) _ => "${r} of ${s}"
                                 ^
                                 Here
Syntactic Context: OtherExpr.

-- Parse Error -------------------------------------------------- main/foo.flix

>> Parse Error: Expected 'type' or 'def' before '=>'

3 |         case Card.Card(r, s) _ => "${r} of ${s}"
                                   ^^
                                   Here
Syntactic Context: Instance.
```
**Reasoning**: 

First error is because parser expects '=>' but finds '_'. This stops parsing of a match-case and returns into the match-expression rule. 

Next error is because the match-expression rule, seeing that it is not at the start of a new match-case, expects a closing '}'. Then control is returned to the instance-body loop. 

The final error is because the instance-body sees something that does not look like a type def or a new definition, namely "=>".  It then skips ahead until a stable spot is found, which ends up being EOF.

### CODE REVIEW

**Comment by herluf-ba** [comment]
I think I need to reconsider the `previousSourcePosition`. It's not consistent in this example. I feel like the old way, which is used on the last of the 3 errors, is more intuitive.

**Comment by magnus-madsen** [comment]
Lets add test cases: Just grab the ticket id, copy the source program, and slam that bad boy into TestParser:

```
test("Regression.TICKETID") {
...
}
```

**Comment by magnus-madsen** [comment]
Indeed the program is very broken, so it is sensible that it would trigger multiple errors before recovery hits.

File: main/src/ca/uwaterloo/flix/api/Flix.scala [hunk 1]
```diff
@@ -547,8 +547,8 @@ class Flix {
     val result = for {
       afterReader <- Reader.run(getInputs)
       afterLexer <- Lexer.run(afterReader, cachedLexerTokens, changeSet)
-      afterParser <- Parser.run(afterReader, entryPoint, cachedParserAst, changeSet)
-      afterWeeder <- Weeder.run(afterParser, cachedWeederAst, changeSet)
+//      afterParser <- Parser.run(afterReader, entryPoint, cachedParserAst, changeSet)
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/api/Flix.scala:550]: This should be undone. We are not making these changes just yet :)

**Comment by magnus-madsen** [comment]
Note that the bug in https://github.com/flix/flix/pull/7660 is separate from this.

Note also that some test cases fail :)

File: main/src/ca/uwaterloo/flix/api/Flix.scala (hunk 1 above)
Comment (herluf-ba) [reply main/src/ca/uwaterloo/flix/api/Flix.scala:550]: Yea haha, Will do!

**Review by magnus-madsen — APPROVED** [review]
