### PR TITLE
fix: parser stuck in effect declaration

### LINKED ISSUE #8326: Parser is stuck on eff
```
eff Print {
    eff
}
```

### PR DESCRIPTION
**Pull request by magnus-madsen**
Fixes #8326

### CODE REVIEW

File: main/src/ca/uwaterloo/flix/language/ast/TokenKind.scala [hunk 1]
```diff
@@ -426,6 +426,17 @@ sealed trait TokenKind {
     case _ => false
   })
 
+  /**
+    * Checks if this token is one of the [[TokenKind]]s that can validly appear as the first token in a declaration within an effect.
+    * Note that a CommentDoc, a Modifier and/or an annotation may lead such a declaration.
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/ast/TokenKind.scala:431]: I copy-pasted this.

The comment about modifier is wrong. But now its consistently wrong with all the `isFoo`.

**Review by mlutze — APPROVED** [review]
