### PR TITLE
fix: `SourceLocation`s on declarations

### LINKED ISSUE #7783: Parser: `SourceLocation` on declarations is imprecise.
Using the "source" links on [api.flix.dev](https://api.flix.dev) it's clear that source locations on definitions are wrong.
Specifically `beginLine` and `endLine` are wrong.

image

### PR DESCRIPTION
**Pull request by herluf-ba**
Closes #7783 

The issue was that a doc-comment with no text was read as a line-comment. That seems innocent but we have the habit of writing:
```scala
///
/// The comment about gets read as a line-comment.
///
pub type alias Static = IO
```

### CODE REVIEW

File: main/src/ca/uwaterloo/flix/language/phase/Lexer.scala [hunk 1]
```diff
@@ -1021,31 +1020,26 @@ object Lexer {
...
    */
-  private def acceptLineComment()(implicit s: State): TokenKind = {
-    while (!eof()) {
-      if (peek() == '\n') {
-        return TokenKind.CommentLine
-      } else {
-        advance()
-      }
+  private def acceptLineOrDocComment()(implicit s: State): TokenKind = {
+//    advance() // Eat one slash.
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/phase/Lexer.scala:1026]: Commented code

**Review by magnus-madsen — APPROVED** [review]
