### PR TITLE
fix: effect parsing

### LINKED ISSUE #8800: Precedence error with effect notation
`ef - IO + Crash` is parsed as `ef - (IO + Crash)`

### PR DESCRIPTION
**Pull request by JonathanStarup**
Fixes  #8800

### CODE REVIEW

**Comment by magnus-madsen** [comment]
A few test cases might be useful?

File: main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala [hunk 1]
```diff
@@ -1116,19 +1116,6 @@ class TestTyper extends AnyFunSuite with TestUtils {
...
   }
 
-  test("TestCaseSetAnnotation.04") {
-    val input =
-      """
-        |restrictable enum Color[s] {
-        |    case Red, Green, Blue
-        |}
-        |
-        |// Wrong minus parsing
```
Comment (JonathanStarup) [inline main/test/ca/uwaterloo/flix/language/phase/TestTyper.scala:1126]: I removed this test since, as it says, it is verifying that we have the wrong parsing

**Review by magnus-madsen — APPROVED** [review]
