### PR TITLE
fix: annotations and modifiers require decl

### LINKED ISSUE #8416: Writing just `@Dep` should be an error
This program should not be valid:

```
@Dep
```

### PR DESCRIPTION
**Pull request by CasperDN**
Fixes #8416

### CODE REVIEW

File: main/src/ca/uwaterloo/flix/language/phase/Parser2.scala [hunk 1]
```diff
@@ -916,7 +917,14 @@ object Parser2 {
         case TokenKind.KeywordStruct => structDecl(mark)
         case TokenKind.KeywordType => typeAliasDecl(mark)
         case TokenKind.KeywordEff => effectDecl(mark)
-        case TokenKind.Eof => close(mark, TreeKind.CommentList) // Last tokens in the file were comments.
+        case TokenKind.Eof =>
+          if (wasAtEofBeforeAnnotations) {
+            close(mark, TreeKind.CommentList) // Last tokens in the file were comments.
+          } else {
```
Comment (JonathanStarup) [inline main/src/ca/uwaterloo/flix/language/phase/Parser2.scala]: Isn't this else branch the same as the `case at =>` branch? maybe just adding `case TokenKind.Eof if wasAtEofBeforeAnnotations => close(mark, TreeKind.CommentList) // Last tokens in the file were comments.` will keep the logic more uniform?

**Comment by magnus-madsen** [comment]
Seems a bit adhoc. Is there no better way @JonathanStarup ?

**Comment by JonathanStarup** [comment]
I can't think of something better, and considering its a two line addition I think its fine

**Comment by magnus-madsen** [comment]
Why is this only a problem for annotations though?

**Comment by CasperDN** [comment]
I think its due to annotations being allowed at to level (Decls). For most of the parsing EOF would signal an error.

**Review by magnus-madsen — APPROVED** [review]
