### PR TITLE
fix: Disallow java names which aren't also Flix names

### LINKED ISSUE #4666: Require rename in import when Java name isn't valid Flix name
It's possible to import Java classes/interfaces with names that aren't valid Flix names, e.g.:

```
import java.util.Locale$Builder
```

In this case we should error and require that the user renames the class, e.g.:

```
import java.util.{Locale$Builder => Builder}
```

### PR DESCRIPTION
**Pull request by paulbutcher**
Fixes #4666

This works, but I'm not 100% happy with it: I've had to effectively re-implement the definition of `UpperCaseName`. I'd love to use the same code, but I can't see how I could reuse a portion of the parser?

If there is a way, I'd love to hear about it.

### CODE REVIEW

File: main/src/ca/uwaterloo/flix/language/errors/WeederError.scala [hunk 1]
```diff
@@ -864,4 +864,27 @@ object WeederError {
          |""".stripMargin
     })
   }
+
```
Comment (mlutze) [inline main/src/ca/uwaterloo/flix/language/errors/WeederError.scala:867]: We put Scaladoc on error classes.

File: main/src/ca/uwaterloo/flix/language/errors/WeederError.scala [hunk 2]
```diff
@@ -864,4 +864,27 @@ object WeederError {
...
+  case class IllegalJavaClass(name: String, loc: SourceLocation) extends WeederError {
+    def summary: String = "${name} is not a valid Flix identifer."
+
+    def message(formatter: Formatter): String = {
+      import formatter._
+      s"""${line(kind, source.name)}
+         |>> ${red(name)} is not a valid Flix identifer.
+         |
+         |${code(loc, "illegal identifer")}
```
Comment (mlutze) [inline main/src/ca/uwaterloo/flix/language/errors/WeederError.scala:876]: I think we're avoiding the word 'illegal' to sound more friendly. Not sure what the best replacement is though.

File: main/src/ca/uwaterloo/flix/language/phase/Weeder.scala [hunk 3]
```diff
@@ -457,18 +457,19 @@ object Weeder {
   private def visitImport(i0: ParsedAst.Import): Validation[List[WeededAst.Import], WeederError] = i0 match {
     case ParsedAst.Imports.ImportOne(sp1, name, sp2) =>
       val loc = mkSL(sp1, sp2)
-      val ident = Name.Ident(sp1, name.fqn.last, sp2)
-      List(WeededAst.Import.Import(name, ident, loc)).toSuccess
+      val alias = name.fqn.last
+      if (raw"[A-Z][A-Za-z0-9_?]*".r matches alias) {
```
Comment (mlutze) [inline main/src/ca/uwaterloo/flix/language/phase/Weeder.scala:461]: Do we actually allow `?` in our names?

Comment (paulbutcher) [reply main/src/ca/uwaterloo/flix/language/phase/Weeder.scala:461]: Oops! That was meant to be `!` (blush). A good example of why it would be nice to be able to reuse the code in the Parser (I don't suppose you're aware of any way I could do this?)

Comment (mlutze) [reply main/src/ca/uwaterloo/flix/language/phase/Weeder.scala:461]: I don't think the Parboiled API makes it easy to do that. The macros seem to enforce some kind of self-containment of the parser which helps performance but hurts reusability.
