### PR TITLE
fix: separate TypeVarSym and TypeVar source locations

### LINKED ISSUE #2510: Type.Var has no way to distinguish between the declaration site of the variable and the variable itself.
Thus, for syntax highlighting, we cannot highlight both of these occurrences:

image

### PR DESCRIPTION
**Pull request by mlutze**
- changes type parameters to use `TypeVarSym`s instead of `TypeVar`s
- changes scheme quantifiers to use `TypeVarSym`s instead of `TypeVar`s
- changes substitution to use `TypeVarSym`s instead of `TypeVar`s
- adds semantic token for type variable

fixes #2510

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Screenshot? :D

**Comment by mlutze** [comment]
Flixify Dark (no support for type variable tokens)
Screenshot from 2022-03-31 20-20-11

Monokai Dimmed:
Screenshot from 2022-03-31 20-20-54

**Comment by magnus-madsen** [comment]
In Monokai Dimmed, why is the first `a` not red?

**Comment by mlutze** [comment]
> In Monokai Dimmed, why is the first `a` not red?

Someone forgot to visit type parameters :)

**Comment by magnus-madsen** [comment]
Do you want to deal with `FindReferences` and `RenameProvider` while you are at it? :)

**Comment by magnus-madsen** [comment]
Also, did you check if it works correctly for classes and instances? :)

**Comment by mlutze** [comment]
I prefer to do LSP in a separate PR since it will take a lot of learning and experimentation. I'd like this PR to focus on the changes to Substitution, etc. if possible.

**Comment by magnus-madsen** [comment]
OK; I will review it later today. Then we can do LSP in a separate PR.

File: main/src/ca/uwaterloo/flix/language/phase/unification/Substitution.scala [hunk 1]
```diff
@@ -30,12 +30,12 @@ object Substitution {
   /**
     * Returns the singleton substitution mapping the type variable `x` to `tpe`.
     */
-  def singleton(x: Type.KindedVar, tpe: Type): Substitution = {
+  def singleton(x: Symbol.TypeVarSym, tpe: Type): Substitution = {
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/phase/unification/Substitution.scala:33]: Whats the advantanges / disadvantages of using the symbol directly here instead of using Type.KindedVar?

File: main/src/ca/uwaterloo/flix/api/lsp/provider/CompleteProvider.scala [hunk 2]
```diff
@@ -178,8 +178,8 @@ object CompleteProvider {
       * Replaces the text in the given variable symbol `sym` everywhere in the type `tpe`
       * with an equivalent variable symbol with the given `newText`.
       */
-    def replaceText(tvar: Type.Var, tpe: Type, newText: String): Type = tpe match {
-      case Type.KindedVar(sym, loc) if tvar.sym == sym => Type.KindedVar(sym.withText(Some(newText)), loc)
+    def replaceText(tvar: Symbol.TypeVarSym, tpe: Type, newText: String): Type = tpe match {
+      case Type.KindedVar(sym, loc) if tvar == sym => Type.KindedVar(sym.withText(Some(newText)), loc)
```
[the remark this answers is not in the document]
Comment (mlutze) [reply main/src/ca/uwaterloo/flix/api/lsp/provider/CompleteProvider.scala:182]: Yes, it's comparing a symbol with a symbol. But I'll change the name so it's more clear

File: main/src/ca/uwaterloo/flix/language/phase/unification/Substitution.scala (hunk 1 above)
Comment (mlutze) [reply main/src/ca/uwaterloo/flix/language/phase/unification/Substitution.scala:33]: The main reason for this choice is that semantically it makes sense. A `TypeVarSym` represents the declaration/identity of a type variable, while a `KindedVar` represents a usage of it. When we substitute, we look for any reference to a variable, not just a reference to one particular usage of it.

It also follows closely from using TypeVarSyms in type parameters and schemes.
I convinced myself with the analogy:

`Expression.Var R Symbol.VarSym`
`Type.KindedVar R Symbol.KindedTypeVarSym`

for some relation `R` :)

**Comment by magnus-madsen** [comment]
I merged this now, the two minor issues can be fixed in another PR.
