### PR TITLE
fix: add region to `Mpmc`

### LINKED ISSUE #7609: `Mpmc[t]` should have a region and use it during lowering
This does not seem to terminate:

```
def main(): Unit \ IO = 
    region rc {
        let (tx, rx) = Channel.buffered(rc, 100);
        spawn (foo(tx)) @ rc;
        println(Channel.recv(rx));
        println("F")
    }

def foo(tx: Sender[String, r]): Unit \ IO + r = 
    println("A");
    Channel.send("123", tx);
    println("B")
```

### PR DESCRIPTION
**Pull request by JonathanStarup**
Sort of Fixes #7609

### CODE REVIEW

**Review by magnus-madsen — APPROVED** [review]

**Comment by JonathanStarup** [comment]
I missed a place where Channel types are destructed

File: main/src/ca/uwaterloo/flix/language/phase/Lowering.scala [hunk 1]
```diff
@@ -1644,10 +1645,25 @@ object Lowering {
...
+    * The type of a channel which can transmit variables of type `tpe1` in region `tpe2`.
+    */
+  private def mkChannelTpe(tpe1: Type, tpe2: Type, loc: SourceLocation): Type = {
+    Type.Apply(Type.Apply(Types.ChannelMpmc, tpe1, loc), tpe2, loc)
+  }
+
+  /**
+    * Returns `(t1, t2)` where `tpe = Concurrent.Channel.Mpmc[t1, t2]`.
+    */
+  private def extractChannelTpe(tpe: Type): (Type, Type) = eraseAliases(tpe) match {
```
Comment (JonathanStarup) [inline main/src/ca/uwaterloo/flix/language/phase/Lowering.scala:1664]: This `eraseAliases` seems ad hoc, but I am just maintaining behaviour from before

File: main/src/ca/uwaterloo/flix/language/phase/Monomorpher.scala [hunk 2]
```diff
@@ -732,7 +732,7 @@ object Monomorpher {
     */
   private def specializeDef(defn: LoweredAst.Def, tpe: Type)(implicit ctx: Context, root: LoweredAst.Root, flix: Flix): Symbol.DefnSym = {
     // Unify the declared and actual type to obtain the substitution map.
-    val subst = infallibleUnify(defn.spec.declaredScheme.base, tpe)
+    val subst = infallibleUnify(defn.spec.declaredScheme.base, tpe, defn.sym)
```
Comment (JonathanStarup) [inline main/src/ca/uwaterloo/flix/language/phase/Monomorpher.scala:735]: This is unrelated, but it helped me debug and it seems useful to add in general
