### PR TITLE
fix: make Xno-optimizer work

### LINKED ISSUE #4604: --Xno-optimizer has no impact
because missing:

```
xnooptimizer = cmdOpts.xnooptimizer,
```

### PR DESCRIPTION
**Pull request by mlutze**
fixes #4604

### CODE REVIEW

File: main/src/ca/uwaterloo/flix/Main.scala [hunk 1]
```diff
@@ -90,13 +90,19 @@ object Main {
...
       xnoseteffects = cmdOpts.xnoseteffects,
       xnobooleffects = cmdOpts.xnobooleffects,
-      xvirtualthreads = cmdOpts.xvirtualthreads
+      xvirtualthreads = cmdOpts.xvirtualthreads,
+      xnooptimizer = cmdOpts.xnooptimizer,
+      incremental = Options.Default.incremental,
+      target = Options.Default.target,
+      test = Options.Default.test,
+      loadClassFiles = Options.Default.loadClassFiles,
+      xallowredundancies = Options.Default.xallowredundancies
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/Main.scala:105]: What's the point of having default if we are going to do this?

I think either:

- We remove default (forcing you always to choose)
- Or we keep the current system where we start with Options.Default.copy

Comment (mlutze) [reply main/src/ca/uwaterloo/flix/Main.scala:105]: `Default` organizes the defaults well and is used as the basis for `DefaultForTesting` etc.

Comment (magnus-madsen) [reply main/src/ca/uwaterloo/flix/Main.scala:105]: Yes, but still, whats the point of not using it here?

Comment (mlutze) [reply main/src/ca/uwaterloo/flix/Main.scala:105]: So that we get a compilation error if we add an option and forget to update it.

More generally, I think there are two cases we are concerned about:
1. We are specifying almost all of the options (as in this case)
2. We want the defaults except a particular option (as in the `DefaultTest` case)

For 1. it's not appropriate to use `Default` due to lack of compilation protections, but for 2. it's more appropriate since it's less likely that a change to the API would necessitate a change in `DefaultTest`.

Comment (magnus-madsen) [reply main/src/ca/uwaterloo/flix/Main.scala:105]: I am not entirely convinced, but I will take it.

Comment (magnus-madsen) [reply main/src/ca/uwaterloo/flix/Main.scala:105]: Can I then be pedantic and ask you to keep them in the same order as in options? :D
