### PR TITLE
fix: type alias must have body

### LINKED ISSUE #8357: Missing error for undefined type alias
```
type alias Magic
def f(): Magic = ???
def main(): Int32 = 32
```
This works and runs

### PR DESCRIPTION
**Pull request by CasperDN**
Fixes #8357

### CODE REVIEW

File: main/src/ca/uwaterloo/flix/language/phase/Parser2.scala [hunk 1]
```diff
@@ -1252,9 +1252,8 @@ object Parser2 {
       if (at(TokenKind.BracketL)) {
         Type.parameters()
       }
-      if (eat(TokenKind.Equal)) {
-        Type.ttype()
-      }
+      expect(TokenKind.Equal)
+      Type.ttype()
```
Comment (JonathanStarup) [inline main/src/ca/uwaterloo/flix/language/phase/Parser2.scala]: I think the idea of `if (eat(TokenKind.Equal))` is to avoid two parser errors, perhaps this is best of both worlds?
```scala
if (eat(TokenKind.Equal)) {
  Type.ttype()
} else {
  expect(TokenKind.Equal)
}
```

**Comment by magnus-madsen** [comment]
Does this problem happen elsewhere?

**Comment by JonathanStarup** [comment]
I would guess almost certainly. The cause of this is places in the Weeder that says "parser will have done X" and many arent true
