### PR TITLE
fix: added check for unsupported pattern in atom bodies

### LINKED ISSUE #5067: Disallow non-variable and non-constant patterns in body atoms
The grammar for `TypedAst` for constraints has:

```
    sealed trait Body extends TypedAst.Predicate

    object Body {

      case class Atom(pred: Name.Pred, den: Denotation, polarity: Ast.Polarity, fixity: Ast.Fixity, terms: List[TypedAst.Pattern], tpe: Type, loc: SourceLocation) extends TypedAst.Predicate.Body

      case class Guard(exp: TypedAst.Expression, loc: SourceLocation) extends TypedAst.Predicate.Body

      case class Loop(varSyms: List[Symbol.VarSym], exp: TypedAst.Expression, loc: SourceLocation) extends TypedAst.Predicate.Body

    }
```

The safety phase should check that the `terms` passed to `Atom` are only variables and constants.

If not, it should emit a `SafetyError` saying that such patterns are not supported.

### PR DESCRIPTION
**Pull request by AStenbaek**
Fixes #5067

### CODE REVIEW

File: main/src/ca/uwaterloo/flix/language/errors/SafetyError.scala [hunk 1]
```diff
@@ -14,6 +14,27 @@ sealed trait SafetyError extends CompilationMessage {
...
+    def message(formatter: Formatter): String = {
+      import formatter._
+      s"""${line(kind, source.name)}
+         |>> Unexpected pattern in body atom.
+         |
+         |${code(loc, "pattern occurs in this body atom.")}
+         |""".stripMargin
+    }
+
+    // TODO: Proper explain for this!
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/errors/SafetyError.scala:34]: We try not to leave TODOs in the code (preferring issues instead). Here the TODO is so small I would do neither, so just remove the comment.

File: main/src/ca/uwaterloo/flix/language/phase/Safety.scala [hunk 2]
```diff
@@ -572,7 +572,21 @@ object Safety {
     //
     val err2 = checkHeadPredicate(c0.head, unsafeLatVars)
 
-    err1 concat err2
+    val err3 = c0.body.flatMap(s => checkBodyPattern(s))
+
+    err1 concat err2 concat err3
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/phase/Safety.scala:577]: As a style choice, we always use `++`

File: main/src/ca/uwaterloo/flix/language/phase/Safety.scala [hunk 3]
```diff
@@ -572,7 +572,21 @@ object Safety {
...
+  }
+
+  // Performs safety check on the pattern of an atom body.
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/phase/Safety.scala:580]: This should be a:

```
/**
 * comment
 */
```

File: main/src/ca/uwaterloo/flix/language/phase/Safety.scala [hunk 4]
```diff
@@ -572,7 +572,21 @@ object Safety {
...
+  private def checkBodyPattern(p0: Predicate.Body): List[CompilationMessage] = p0 match {
+    case Predicate.Body.Atom(_,_,_,_,terms,_,loc) =>
+      terms.foldLeft[List[SafetyError]](Nil)((acc, term) => term match {
+        case Pattern.Var(_, _, _)
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/phase/Safety.scala:584]: (As a style choice) we don't use Or patterns, instead preferring to write each case. But of course you can still have your wildcard case.

File: main/src/ca/uwaterloo/flix/language/phase/Safety.scala [hunk 5]
```diff
@@ -572,7 +572,21 @@ object Safety {
...
+             | Pattern.Wild(_, _)
+             | Pattern.Cst(_, _, _) => acc
+        case _ => UnexpectedPatternInBodyAtom(loc) :: acc
+      }).reverse
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/phase/Safety.scala:588]: This is not required, since error messages are sorted by source loc later.

File: main/test/ca/uwaterloo/flix/language/phase/TestSafety.scala [hunk 6]
```diff
@@ -18,14 +18,36 @@ package ca.uwaterloo.flix.language.phase
...
+  test("UnexpectedBodyAtomPattern.02") {
+    val input =
+      """
+        |pub def f(): #{ A(Int32), B(Option[Int32]) } = #{
+        |    A(1) :- B(Some(2)).
+        |}
+      """.stripMargin
+    val result = compile(input, Options.TestWithLibAll)
+    expectError[UnexpectedPatternInBodyAtom](result)
+  }
```
Comment (magnus-madsen) [inline main/test/ca/uwaterloo/flix/language/phase/TestSafety.scala:49]: Could we do a few more tests, eg. with `Result/List`, but also with more than one bod atom?

Thanks!

**Review by magnus-madsen — COMMENTED** [review]
Looks good.

I added lots of small comments about our style. 

Do another iteration and then it can probably be merged :)

**Comment by magnus-madsen** [comment]
- You can mark comments as "resolved" when they are done.
- I forgot you ask you to put your name in `AUTHORS.md` :)

**Comment by magnus-madsen** [comment]
@mlutze note one of these gives illegal semver.

**Comment by magnus-madsen** [comment]
Congrats on the first merged PR. Onwards and upwards!

**Comment by mlutze** [comment]
> @mlutze note one of these gives illegal semver.

My brittle code comes back to haunt me...
