### PR TITLE
fix: enforce predicate arity greater than zero

### LINKED ISSUE #10901: Disallow `inject .. into ../0` in Weeder

### PR DESCRIPTION
**Pull request by magnus-madsen**
Fixes #10901

### CODE REVIEW

**Comment by magnus-madsen** [comment]
@jaschdoc I am reusing the same error-- which I think is OK.

File: main/src/ca/uwaterloo/flix/language/errors/WeederError.scala [hunk 1]
```diff
@@ -494,6 +494,23 @@ object WeederError {
...
+    * An error raised to indicate an illegal predicate arity.
+    *
+    * @param loc the location where the error occurs.
+    */
+  case class IllegalPredicateArity(loc: SourceLocation) extends WeederError {
+    override def summary: String = "Illegal predicate arity."
+
+    override def message(formatter: Formatter): String = {
+      import formatter.*
+      s""">> Illegal predicate arity. Arity must be an integer larger than zero.
```
Comment (JonathanStarup) [inline main/src/ca/uwaterloo/flix/language/errors/WeederError.scala:507]: If I write `inject .. into Pred/1_000` the error says `Arity must be an integer larger than zero`

Comment (JonathanStarup) [reply main/src/ca/uwaterloo/flix/language/errors/WeederError.scala:507]: I'd just add a `hint: String` argument to `IllegalPredicateArity`

Comment (magnus-madsen) [reply main/src/ca/uwaterloo/flix/language/errors/WeederError.scala:507]: Because 1_000 is a different token or what?

Comment (JonathanStarup) [reply main/src/ca/uwaterloo/flix/language/errors/WeederError.scala:507]: `1_000` and `1000` and `0xFF` are all just LiteralInt

`case None` in weeder is hit because `token.text` is either a hex number and/or a number with `_`.

The old error was also not super good but I think just having one be `hint = "Arity must be larger than zero."` and the other be `hint = "Arity can not use '_' or be a hex-number"` could be nice

Comment (magnus-madsen) [reply main/src/ca/uwaterloo/flix/language/errors/WeederError.scala:507]: You can merge and then create a follow up PR

Comment (JonathanStarup) [reply main/src/ca/uwaterloo/flix/language/errors/WeederError.scala:507]: To me it makes sense to do here, is it just a time budget thing?

Comment (magnus-madsen) [reply main/src/ca/uwaterloo/flix/language/errors/WeederError.scala:507]: Yes. But feel free to create a new PR or a ticket.

For me I think the interesting case is when you forget the arity. What happens there?

Comment (JonathanStarup) [reply main/src/ca/uwaterloo/flix/language/errors/WeederError.scala:507]: parser says "unexpected xyz, expected literal int" i think

**Review by JonathanStarup — APPROVED** [review]
