### PR TITLE
Minor cleanup of Pattern Match Exhaustiveness (Fixes #468)

### LINKED ISSUE #468: Minor Cleanup of Pattern Match Exhaustiveness
- Maybe I missed something, but should `Expressions.checkPats` not be recursive? (If you have pattern match within a pattern match). See below.
- Don't use `Integer`, but use `Int`. 
- Don't use `getClass`.
- Re-order `TypeConstructor` (and every use of it in a pattern match) to occur in the order of expressions, e.g. Unit, True, False, etc. etc.

This:

```
def f(l: List[Int]): Int = let foo = 42 ;
    match l with {
        case Nil => 42
    }
```

should fail, but does not.

### PR DESCRIPTION
**Pull request by jmittert**
- Made the check recursive on expressions (oops)
- Use Int instead of Integer
- Don't use getClass
- Reorder type constructor
- Added a few more tests for nested cases

### CODE REVIEW

File: main/test/ca/uwaterloo/flix/language/phase/TestParser.scala [hunk 1]
```diff
@@ -1456,27 +1456,27 @@ class TestParser extends FunSuite with TestUtils {
 
   test("Expression.MatchLambda.05") {
     val input = "def f: Option[Int] -> Int = match None -> 42"
-    run(input, core = false)
+    expectError[NonExhaustiveMatchError](new Flix().addStr(input).compile())
```
Comment (jmittert) [inline main/test/ca/uwaterloo/flix/language/phase/TestParser.scala]: The MatchLambdas here are non exhaustive, but I wonder if between those and the Let Matches, maybe instead of not letting them be non exhaustive, maybe we don't check them, or compile them to have and implicit _ -> MatchError . It seems to me that if you're doing something like the above, you fully know that it's non exhaustive, but it still seems like an nice feature to have in the case where you know that it can't be a Some(_), but you can't prove it.

Comment (magnus-madsen) [inline main/test/ca/uwaterloo/flix/language/phase/TestParser.scala]: I think we should warn for lambda matches too, if they are not exhaustive. 

You would still be able to use LambdaMatch for both singleton enums (common) and tuples (common)

**Comment by magnus-madsen** [comment]
Nice, good job!
