### PR TITLE
fix: bug in `HighlightProvider.scala`

### LINKED ISSUE #8610: Crash in `HighlightProvider`
```
#
# An unexpected error has been detected by the Flix compiler:
#
#   key not found: TimeUnit.Nano
#
# This is a bug in the Flix compiler. Please report it here:
#
# https://github.com/flix/flix/issues
#
# -- Flix Compiler --
#
# Flix Version : 0.50.0
#   incremental: All
#
# -- Java Virtual Machine --
#
# JVM Version  : 21 (2023-09-19)
# JVM Vendor   : Eclipse Adoptium
# JAVA_HOME    : C:\Program Files\Eclipse Adoptium\jdk-21.0.0.35-hotspot
# System       : Windows 10 (10.0)
#
# -- Stack Trace --
java.util.NoSuchElementException: key not found: TimeUnit.Nano
	at scala.collection.immutable.BitmapIndexedMapNode.apply(HashMap.scala:674)
	at scala.collection.immutable.HashMap.apply(HashMap.scala:132)
	at ca.uwaterloo.flix.api.lsp.provider.HighlightProvider$.highlightCase(HighlightProvider.scala:161)
	at ca.uwaterloo.flix.api.lsp.provider.HighlightProvider$.processHighlight(HighlightProvider.scala:31)
```

### PR DESCRIPTION
**Pull request by magnus-madsen**
Fixes #8610

### CODE REVIEW

**Comment by magnus-madsen** [comment]
We will need someone to do a general pass through LSP and check for these things.

File: main/src/ca/uwaterloo/flix/api/lsp/provider/HighlightProvider.scala [hunk 1]
```diff
@@ -158,9 +158,15 @@ object HighlightProvider {
   }
 
   private def highlightCase(uri: String, sym: Symbol.CaseSym)(implicit index: Index, root: Root): JObject = {
-    val write = (root.enums(sym.enumSym).cases(sym).loc, DocumentHighlightKind.Write)
+    val write = root.enums.get(sym.enumSym) match {
```
Comment (mlutze) [inline main/src/ca/uwaterloo/flix/api/lsp/provider/HighlightProvider.scala:161]: feels like a comprehension might be cleaner

**Review by mlutze — APPROVED** [review]

File: main/src/ca/uwaterloo/flix/api/lsp/provider/HighlightProvider.scala (hunk 1 above)
Comment (magnus-madsen) [reply main/src/ca/uwaterloo/flix/api/lsp/provider/HighlightProvider.scala:161]: Yeah, but I think all of this code has to be refactored.
