### PR TITLE
fix: handler unit padding location

### LINKED ISSUE #10092: Bad Semantic Token in Handler
Image

As you can see, most tokens in the handler is colored green. This is because the lsp returned a HUGE type token that spans the whole op. This used to be suppressed since it's a multi-line token. But now it's rendered.

I debug it and find out that this token is from the fparams in:
https://github.com/flix/flix/blob/baf70ce9c3bceed42efbe1d8209410ce19fd1a28/main/src/ca/uwaterloo/flix/api/lsp/provider/SemanticTokensProvider.scala#L598-L608

Here is fparam include the hole op(see the first screenshot). 

Should we just stop visiting the fparam here to avoid this problem?

### PR DESCRIPTION
**Pull request by JonathanStarup**
fixes #10092

Also fixes a an issue around people calling their handler continuation `_unit`, e.g. `def op(_unit) = 42`

### CODE REVIEW

File: main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala [hunk 1]
```diff
@@ -1793,11 +1793,24 @@ object Weeder2 {
...
+        // `def f(x, y, ..)` is unchanged.
+        fparams0 match {
+          case fparam :: Nil =>
+            // Since a continuation argument must always be there, the underlying function needs a
+            // unit param. For example `def f(k)` becomes `def f(_unit: Unit, k)`.
+
+            // The new param has the zero-width location of the actual argument.
+            val loc = SourceLocation.zeroPoint(isReal = false, fparam.loc.sp1)
+            // We already have an argument, which could be called "_unit", so use a backup.
+            val name = if (fparam.ident.name == "_unit") "_unit1" else "_unit"
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala:1808]: ???

Comment (JonathanStarup) [reply main/src/ca/uwaterloo/flix/language/phase/Weeder2.scala]: Turns out expressions don't check for duplicate `_unit` names, so I can omit this.

**Review by magnus-madsen — APPROVED** [review]
