### PR TITLE
Check Negatively Bound Wildcards

### LINKED ISSUE #1973: New Solver - Negation - bug or invalid program?
I have a program that worked with the old solver but crashes with the new solver - I'm not 100% sure that its use of negation is valid but a runtime crash is a bit harsh...

The program uses negation assert a missing `StringValue` and assign "NONE" to location - the query answer `Location` should provide a result for all three keys ("x3" should be "NONE"):

~~~

rel StringValue(id: String, field: String, value: String)
rel Key(id: String)
rel Location(id: String, value: String)

def locations(): #{ Location, Key, StringValue | r } = solve #{
    StringValue("x1", "LOCATION", "Europe").
    StringValue("x2", "LOCATION", "Bermuda").
    Key("x1").
    Key("x2").
    Key("x3").

    Location(key, loc) :- 
        Key(key),
        StringValue(key, "LOCATION", loc).

    Location(key, "NONE") :- 
        Key(key),
        not StringValue(key, "LOCATION", _).
}


def main(_args: Array[String]): Int32 & Impure = 
    test01();
    0

def test01(): Unit & Impure =     
    query locations() select (x1, x2) from Location(x1, x2) 
        |> Array.foreach(println)
        
~~~        

I've added more output to Fixpoint.Compiler.flix to print the atom that generates the error:

~~~

    def augmentBody(body: Array[BodyPredicate[v]]): Array[(BodyPredicate[v], RowVar)] with ToString[v] =
        Array.mapWithIndex(atom -> i -> match atom {
            case BodyAtom(predSym, _, Polarity.Positive, _) => (atom, RowVar.Named("${predSym}$${i}"))
            case _ => (atom, RowVar.Named("IfYouSeeThisYouFoundABug - ```${atom}```"))
        }, body) as & Pure
        
~~~        

The program trace is: 

~~~

✓ Reader                                    10.7ms
✓ Parser                                  4230.4ms
✓ Weeder                                  1410.3ms
✓ Namer                                   1193.9ms
✓ Resolver                                1562.7ms
✓ Typer                                   3751.1ms
✓ Instances                                 56.5ms
✓ Stratifier                               148.6ms
    Compute Dependency Graph             (  46.1ms)
    Compute Stratification               (  98.5ms)
✓ PatternExhaustiveness                    555.8ms
✓ Redundancy                               487.0ms
✓ Safety                                    42.6ms
✓ Documentor                                 0.0ms
✓ Lowering                                 131.7ms
✓ Monomorph                                447.3ms
✓ Simplifier                               225.2ms
✓ ClosureConv                              416.6ms
✓ LambdaLift                               163.7ms
✓ Tailrec                                   19.3ms
✓ Optimizer                                 76.1ms
✓ TreeShaker                                90.7ms
✓ VarNumbering                              17.2ms
✓ Finalize                                 230.2ms
✓ Eraser                                   186.1ms
✓ JvmBackend                              6826.5ms
    CodeGen                              (2205.8ms)
    WriteClasses                         (4025.0ms)
    LoadClasses                          ( 411.9ms)
    LoadMethods                          ( 173.0ms)
Compiled 40,164 lines in 22.3 sec. (1,803 lines/sec).
********************************************************************************
**
**  BUG: Illegal term IfYouSeeThisYouFoundABug - ```not StringValue(key, LOCATION, _)```[2]
**
********************************************************************************

Hole '?panic' at Prelude.flix:120:5

HoleError{hole='?panic', location=flix.runtime.ReifiedSourceLocation@606a3075}
	at Def$bug!$191254.invoke(Unknown Source)
	at Array.Def$initHelper$191281.invoke(Unknown Source)
	at Array.Def$init$190633.invoke(Unknown Source)
	at Fixpoint.Clo$evalBoolExp$192254$224355.invoke(Unknown Source)
	at List.Def$forall$193300.invoke(Unknown Source)
	at Fixpoint.Def$evalOp$192232.invoke(Unknown Source)
	at RedBlackTree.Def$foreach$191275.invoke(Unknown Source)
	at RedBlackTree.Def$foreach$191275.invoke(Unknown Source)
	at Array.Def$foreachHelper$193296.invoke(Unknown Source)
	at Fixpoint.Def$interpretWithDatabase$190689.invoke(Unknown Source)
	at Fixpoint.Def$solveWithStratification$189592.invoke(Unknown Source)
	at Def$locations$184894.invoke(Unknown Source)
	at Def$test01.invoke(Unknown Source)
	at Def$main.invoke(Unknown Source)
	at Ns.m_main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.$anonfun$link$1(JvmBackend.scala:263)
	at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.$anonfun$getCompiledMain$2(JvmBackend.scala:224)
	at ca.uwaterloo.flix.language.phase.jvm.JvmBackend$.$anonfun$getCompiledMain$2$adapted(JvmBackend.scala:222)
	at ca.uwaterloo.flix.Main$.main(Main.scala:196)
	at ca.uwaterloo.flix.Main.main(Main.scala)

Process finished with exit code 1

~~~

With the old solver, the program runs as I expect...

~~~


rel StringValue(id: String, field: String, value: String)
rel Key(id: String)
rel Location(id: String, value: String)

def locations(): #{ Location, Key, StringValue | r } = solve #{
    StringValue("x1", "LOCATION", "Europe").
    StringValue("x2", "LOCATION", "Bermuda").
    Key("x1").
    Key("x2").
    Key("x3").

    Location(key, loc) :- 
        Key(key),
        StringValue(key, "LOCATION", loc).

    Location(key, "NONE") :- 
        Key(key),
        not StringValue(key, "LOCATION", _).
}


def main(_args: Array[String]): Int32 & Impure = 
    test01();
    0

def test01(): Unit & Impure =     
    (project Location locations())
        |> unsafeToString
        |> println
        
~~~

Output:

~~~

✓ Reader                                    33.0ms
✓ Parser                                  2764.1ms
✓ Weeder                                   881.7ms
✓ Namer                                   1315.5ms
✓ Resolver                                1790.4ms
✓ Typer                                   3931.3ms
✓ Instances                                 68.5ms
✓ Stratifier                               375.9ms
    Compute Dependency Graph             ( 132.5ms)
    Compute Stratification               ( 135.5ms)
✓ PatternExhaustiveness                    680.0ms
✓ Redundancy                              1090.3ms
✓ Safety                                   174.7ms
✓ Documentor                                 0.0ms
✓ Monomorph                                673.6ms
✓ Simplifier                              4418.1ms
✓ ClosureConv                             1084.4ms
✓ LambdaLift                              2640.5ms
✓ Tailrec                                   18.7ms
✓ Optimizer                                265.6ms
✓ TreeShaker                               173.8ms
✓ VarNumbering                             147.2ms
✓ Finalize                                1553.9ms
✓ Eraser                                  2139.8ms
✓ JvmBackend                              5140.4ms
    CodeGen                              (2459.0ms)
    WriteClasses                         (2583.6ms)
    LoadClasses                          (  38.3ms)
    LoadMethods                          (  14.2ms)
Compiled 36,859 lines in 31.4 sec. (1,175 lines/sec).
Solved in 56 msec. (init: 23 msec, readers: 11 msec, writers: 18 msec)
Initial Facts: 5. Total Facts: 8.
Throughput: 140 facts per second.
Location
------+---------
 col0 | col1    
------+---------
 x3   | NONE    
------+---------
 x1   | Europe  
------+---------
 x2   | Bermuda 
------+---------



Process finished with exit code 0

~~~

Is this a bug with the new solver, or was my program wrong?

### PR DESCRIPTION
**Pull request by JonathanStarup**
Fixes #1973

The program
```
def main(_args: Array[String]) : Int32 & Impure =
    let p = #{ A(1, 2). B(1) :- not A(1, _). };
    query p select x from B(x) |> println;
    0
```
results in this error:
```
-- Safety Error -------------------------------------------------- examples\misc\test.flix

>> Illegal negatively bound wildcard '_'.

2 |     let p = #{ A(1, 2). B(1) :- not A(1, _). };
                                    ^^^^^^^^^^^
                                    the wildcard occurs in this negated atom.



Compilation failed with 1 error(s).
```
When `_` is changed to `_x` the error is:
```
-- Safety Error -------------------------------------------------- examples\misc\test.flix

>> Illegal negatively bound variable '_x'.

2 |     let p = #{ A(1, 2). B(1) :- not A(1, _x). };
                                    ^^^^^^^^^^^^
                                    the variable occurs in this negated atom.



Compilation failed with 1 error(s).
``` 
When `B(1) :- not A(1, _).` is changed to `B(x) :- not A(1, x).` in the original program the error is:
```
-- Safety Error -------------------------------------------------- examples\misc\test.flix

>> Illegal non-positively bound variable 'x'.

2 |     let p = #{ A(1, 2). B(x) :- not A(1, x). };
                                    ^^^^^^^^^^^
                                    the variable occurs in this negated atom.


Tip: Ensure that the variable occurs in at least one positive atom.


Compilation failed with 1 error(s).
```

### CODE REVIEW

File: main/src/ca/uwaterloo/flix/language/phase/Safety.scala [hunk 1]
```diff
@@ -270,14 +284,46 @@ object Safety extends Phase[Root, Root] {
       case Polarity.Negative =>
         // Compute the free variables in the terms which are *not* bound by the lexical scope.
         val freeVars = terms.flatMap(freeVarsOf).toSet intersect quantVars
+        val errors = checkNegativeWildcards(terms, loc)
```
Comment (JonathanStarup) [inline main/src/ca/uwaterloo/flix/language/phase/Safety.scala:287]: @magnus-madsen This is the only new part of safety, I got a bit sidetracked looking at Intellij warnings. I can remove the reformatting if you prefer but maybe we could discuss some style guidelines in the compiler. Here I tried to eliminate unused variables mostly.

File: main/src/ca/uwaterloo/flix/language/errors/SafetyError.scala [hunk 2]
```diff
@@ -8,24 +8,79 @@ import ca.uwaterloo.flix.util.vt.VirtualTerminal
...
 
 object SafetyError {
 
+  /**
+    * Creates an IllegalNonPositivelyBoundVariable or IllegalNegativelyBoundWildVariable error
+    * depending on `sym.isWild`.
+    *
+    * @param loc the position of the body atom containing the illegal variable.
+    */
+  def makeIllegalNonPositivelyBoundVariableError(sym: Symbol.VarSym, loc: SourceLocation): SafetyError =
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/errors/SafetyError.scala:23]: We try to keep all the error classes "dumb" and I think this check is only used in once place, so I would move it there instead. Its better to keep the "business logic" in the phases.

File: main/src/ca/uwaterloo/flix/language/errors/SafetyError.scala [hunk 3]
```diff
@@ -8,24 +8,79 @@ import ca.uwaterloo.flix.util.vt.VirtualTerminal
...
+    if (sym.isWild) IllegalNegativelyBoundWildVariable(sym, loc) else IllegalNonPositivelyBoundVariable(sym, loc)
+
   /**
     * An error raised to indicate an illegal use of a non-positively bound variable in a negative atom.
+    * The symbol must not be wild.
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/errors/SafetyError.scala:28]: Remove comment :)

File: main/src/ca/uwaterloo/flix/language/errors/SafetyError.scala [hunk 4]
```diff
@@ -8,24 +8,79 @@ import ca.uwaterloo.flix.util.vt.VirtualTerminal
...
+        vt << NewLine
+        vt << Underline("Tip:") << " Ensure that the variable occurs in at least one positive atom." << NewLine
+      }
+      vt
+    }
+  }
+
+  /**
+    * An error raised to indicate an illegal use of a wild variable in a negative atom.
+    * The symbol must be wild.
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/errors/SafetyError.scala:52]: Kill comment too.

File: main/src/ca/uwaterloo/flix/language/errors/SafetyError.scala [hunk 5]
```diff
@@ -8,24 +8,79 @@ import ca.uwaterloo.flix.util.vt.VirtualTerminal
...
+      vt
+    }
+  }
+
+  /**
+    * An error raised to indicate an illegal use of a wildcard in a negative atom.
+    *
+    * @param loc the position of the body atom containing the illegal wildcard.
+    */
+  case class IllegalNegativelyBoundWildcard(loc: SourceLocation) extends SafetyError {
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/errors/SafetyError.scala:75]: Whats the difference between IllegalNegativelyBoundWildcard and IllegalNegativelyBoundWildVariable? Maybe we need better names?

File: main/src/ca/uwaterloo/flix/language/phase/Safety.scala (hunk 1 above)
Comment (magnus-madsen) [reply main/src/ca/uwaterloo/flix/language/phase/Safety.scala:287]: Thats good! We are slowing moving towards removing unused vars-- like in Flix.

File: main/src/ca/uwaterloo/flix/language/phase/Safety.scala [hunk 6]
```diff
@@ -270,14 +284,46 @@ object Safety extends Phase[Root, Root] {
...
 
         // Check if any free variables are not positively bound.
-        ((freeVars -- posVars) map {
-          case unboundVar => SafetyError.IllegalNonPositivelyBoundVariable(unboundVar, loc)
-        }).toList
+        errors ++ ((freeVars -- posVars) map (unboundVar => SafetyError.makeIllegalNonPositivelyBoundVariableError(unboundVar, loc))).toList
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/phase/Safety.scala:290]: This is not easy to read.

I would make two local variables with meaningful names and then you can ++ them at the end.

File: main/src/ca/uwaterloo/flix/language/phase/Safety.scala [hunk 7]
```diff
@@ -270,14 +284,46 @@ object Safety extends Phase[Root, Root] {
...
 
+  /**
+    * @param loc the location of the atom containing the terms.
+    */
+  private def checkNegativeWildcards(terms: List[TypedAst.Pattern], loc: SourceLocation): List[CompilationError] = {
+    terms.flatMap(checkNegativeWildcards(_, loc))
+  }
+
+  /**
+    * @param loc the location of the atom containing the term.
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/phase/Safety.scala:302]: Missing comment.

File: main/src/ca/uwaterloo/flix/language/phase/Safety.scala [hunk 8]
```diff
@@ -270,14 +284,46 @@ object Safety extends Phase[Root, Root] {
...
-          case unboundVar => SafetyError.IllegalNonPositivelyBoundVariable(unboundVar, loc)
-        }).toList
+        errors ++ ((freeVars -- posVars) map (unboundVar => SafetyError.makeIllegalNonPositivelyBoundVariableError(unboundVar, loc))).toList
     }
   }
 
+  /**
+    * @param loc the location of the atom containing the terms.
+    */
+  private def checkNegativeWildcards(terms: List[TypedAst.Pattern], loc: SourceLocation): List[CompilationError] = {
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/phase/Safety.scala:297]: Move this after the next method.

File: main/src/ca/uwaterloo/flix/language/phase/Safety.scala [hunk 9]
```diff
@@ -270,14 +284,46 @@ object Safety extends Phase[Root, Root] {
...
+    terms.flatMap(checkNegativeWildcards(_, loc))
+  }
+
+  /**
+    * @param loc the location of the atom containing the term.
+    */
+  @tailrec
+  private def checkNegativeWildcards(term: TypedAst.Pattern, loc: SourceLocation): List[CompilationError] = term match {
```
Comment (magnus-madsen) [inline main/src/ca/uwaterloo/flix/language/phase/Safety.scala:305]: I think we should just rename these to `visitPat` and `visitPats`. Thats the usual names.

File: main/test/ca/uwaterloo/flix/language/phase/TestSafety.scala [hunk 10]
```diff
@@ -41,33 +40,56 @@ class TestSafety extends FunSuite with TestUtils {
...
       """.stripMargin
     val result = compile(input, DefaultOptions)
-    expectError[IllegalNonPositivelyBoundVariable](result)
+    expectError[IllegalNegativelyBoundWildVariable](result)
+  }
+
+  test("NegativelyBoundWildcard.01") {
+    val input =
+      """
+        |pub def f(): #{ A(Int), B(Int) } = solve {
```
Comment (magnus-madsen) [inline main/test/ca/uwaterloo/flix/language/phase/TestSafety.scala:76]: I would do some tests without `solve` since it is not required for the error to trigger.

File: main/test/ca/uwaterloo/flix/language/phase/TestSafety.scala [hunk 11]
```diff
@@ -41,33 +40,56 @@ class TestSafety extends FunSuite with TestUtils {
...
+  test("NegativelyBoundWildcard.02") {
+    val input =
+      """
+        |pub def f(): #{ A(Int), B(Int) } = solve {
+        |    A(1) :- not B(_), A(_).
+        |}
+      """.stripMargin
+    val result = compile(input, DefaultOptions)
+    expectError[IllegalNegativelyBoundWildcard](result)
   }
```
Comment (magnus-madsen) [inline main/test/ca/uwaterloo/flix/language/phase/TestSafety.scala:93]: Add 2-3 more tests.

File: main/src/ca/uwaterloo/flix/language/errors/SafetyError.scala (hunk 5 above)
Comment (JonathanStarup) [reply main/src/ca/uwaterloo/flix/language/errors/SafetyError.scala:75]: Wildcard just doesn't have a symbol, so I just made them different errors, could just have a string or optional VarSym I suppose. And the difference from these to the third error is just non-positively <-> negatively and the tip.

File: main/src/ca/uwaterloo/flix/language/phase/Safety.scala (hunk 1 above)
Comment (JonathanStarup) [reply main/src/ca/uwaterloo/flix/language/phase/Safety.scala:287]: Could be nice with Flix like _something variables so you can glance what information is being ignored.

Comment (magnus-madsen) [reply main/src/ca/uwaterloo/flix/language/phase/Safety.scala:287]: Yes. However the problem is that such names get outdated and are not updated during refactorings.

File: main/src/ca/uwaterloo/flix/language/errors/SafetyError.scala (hunk 5 above)
Comment (magnus-madsen) [reply main/src/ca/uwaterloo/flix/language/errors/SafetyError.scala:75]: I see. I think the difference is minimal, so I would just combine them. What do you think?

Comment (JonathanStarup) [reply main/src/ca/uwaterloo/flix/language/errors/SafetyError.scala:75]: I think its nice to have them both to have more specific errors

**Comment by magnus-madsen** [comment]
Thanks!
